logto-io/docs

docs/docs/tutorials/get-started/_connectors-wip.md
docs/docs/tutorials/get-started/customize-sign-in-experience.md
docs/docs/tutorials/get-started/enable-passcode-sign-in.mdx
docs/docs/tutorials/get-started/enable-social-sign-in.md
docs/docs/tutorials/get-started/enable-social-sign-in.mdx

- enable social sign-in tutorial
- align content and wording between social/passcode tutorials

docs(en-US): enable social sign-in

---

docs/docs/recipes/integrate-logto/traditional.mdx

Add a tutorial post: Integrate with traditional web app.
We don't have any traditional web app SDK for v1, so I created a "smallest" express sample: https://github.com/logto-io/express-example, it is written by pure JavaScript for Node and doesn't have lint configured, keep it simple in order that users can follow this tutorial and understand how to integrate Logto to a traditional web app, especially when they are using other framworks or tech stacks.

docs(en-US): tutorial for traditional web

---

src/scss/custom.scss

minor content style update
1. Gives extra space to the main content bottom
2. Set the sidebar menu work-break: break-word
3. Remove the default menu arrow filter as it cause issue under darkmode.
give extra space to the main content

style(docs): minor content style update

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

Move annotation out of bash script block, in order to avoid being copied along with the command on clicking the copy button

refactor: move annotation out of bash script block

---

docs/docs/recipes/protect-your-api/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/README.md
i18n/zh-cn/docusaurus-theme-classic/navbar.json
src/theme/Footer/FooterLayout.tsx

fix some doc site bugs.
1. remove the logto title settings under CN page config
2. update the img element in markdown, as somehow HTML img element src attribute is not processed to proper static file location as expected. 
@logto-io/eng

fix(docs): fix some doc site bugs

---

docs/docs/recipes/manage-users/integrate-logto-data.md
docs/docs/references/users/README.md
docs/docs/references/users/custom-data.md

Replace the term “attribute” with “property”

docs(en-US): replace attribute with property

---

docusaurus.config.js

use absolute url. tested locally

chore: fix footer logo

---

src/scss/custom.scss

adjust side nav font-size
Before:
After:
@eng

style(docs): adjust side nav font-size

---

package.json

`.github/deploy.yml` uses `pnpm build` (not `pnpm deploy`) to deploy docs.
We should append `build:swagger` to `build` in `package.json` to fix the content of API Reference.

fix: deploy docs with swagger.json

---

docs/docs/references/logto-sdk-convention/README.mdx
docs/docs/references/logto-sdk-convention/platform-sdk-convention.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/logto-sdk-convention/README.mdx

- Provide a Chinese version of the Logto SDK Convention summary.
- Support falling back to the English version by removing the file extension type in the navigation link.

docs: logto sdk convention zh-cn

---

src/pages/Api/index.scss
src/pages/Api/index.tsx

Force set `top` and `height` of the sidebar to avoid being scrolled to top with page content and got blocked by header.
You can only beat magic with magic.

fix: page scrolling issue on API page

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

Some environment variables are missing with the Docker instructions. Here is a pull request to fix it.
/

docs: fix docker instructions (missing env vars)

---

docs/docs/references/core/README.mdx

Fix "Frontend proxies" link in "Core Service" page

docs: fix "frontend proxy" link in core service references

---

src/pages/api/index.tsx
tsconfig.json

Add the title "API" to API Reference page
- The full title of API Reference page should `API | Logto Docs` (i.e. page title + ' | ' + website title)
---
Related problem:
After adding the title to the API Reference page, failed to pass `tsc -p tsconfig.json`.
Resolved it by adding `"types": ["@docusaurus/theme-classic"]` in `tsconfig.ts`.
Thanks for the help from @demonzoo 
Locally tested.

fix: add title to api reference page

---

docs/docs/recipes/integrate-logto/fragments/_configure-redirect-uri.mdx

Add whitespace between the `Redirect URI` text and the following code snippet.
Before
After
Locally preview & tested.

fix(docs): fix spacing in _configure-redirect-uri.mdx

---

docs/docs/recipes/configure-connectors/_category_.json
docs/docs/recipes/create-your-connector/_category_.json
docs/docs/recipes/customize-sie/_category_.json
docs/docs/recipes/integrate-logto/_category_.json
docs/docs/recipes/integrate-logto/android.mdx
docs/docs/recipes/integrate-logto/fragments/_apply_authorization_token.md
docs/docs/recipes/integrate-logto/fragments/_further-readings.md
docs/docs/recipes/integrate-logto/fragments/_get_authorization_token.md
docs/docs/recipes/integrate-logto/ios.mdx
docs/docs/recipes/integrate-logto/react.mdx
docs/docs/recipes/integrate-logto/vanilla-js.mdx
docs/docs/recipes/integrate-logto/vue.mdx
docs/docs/recipes/manage-users/_category_.json
docs/docs/recipes/protect-your-api/README.mdx
docs/docs/recipes/protect-your-api/_category_.json
docs/docs/references/resources/README.md

Extract client token request guide from protecting your API to SDK
This PR includes following updates:
1. Make all docs under recipes collapsible as we will show all the language integration guide as subcategories.
2. Refine and simplify some content in API resource and API protection docs.
3. Extract the `Integrate the resources authorization flow into your client application` section from Protect Your API
move the content under each client SDK integration guide.
Next Steps:
2/3:  Extract backend API protection guide to subcategories
3/3: Reorg document structure of integrating Logto with  applications:
- client
- traditional web
- backend
test locally
@logto-io/eng @logto-io/mandatory-reviewers

refactor(doc): extract client token request guide to SDK

---

docs/docs/recipes/integrate-logto/next-js.mdx

Add a section to Next.js SDK instructions for Backend Authorization. It is missing from this SDK's documentation. It follows the same structure as the other ones that already have it explicity documented (React, Vue, Android, VanillaJS, etc.).
No testing needed.

docs(en): add backend authentication section to next.js instructions

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

Add docker host static ip `172.17.0.1` for platforms that doesn't support host domain `host.docker.internal`, e.g. Ubuntu.
N/A

docs: add docker host static ip for platforms that do not support host domain

---

docs/docs/recipes/deployment/README.md

By passing CI=true to a noninteractive execution of alterations,
the command job returns successfully.

docs(en): fix doc for running db alteration

---

docs/docs/recipes/configure-connectors/configure-email-connector.md
docs/docs/recipes/configure-connectors/configure-sms-connector.md
docs/docs/recipes/configure-connectors/configure-social-connector.md
docs/docs/recipes/configure-connectors/custom-social-connector-with-standard-protocols.md
docs/docs/recipes/create-your-connector/connector-file-structure.mdx
docs/docs/recipes/create-your-connector/connector-implementation-guide.mdx
docs/docs/recipes/interact-with-management-api/README.md
docs/docs/tutorials/get-started/explore-management-api.md
docusaurus.config.js
src/theme/BlogPostItem/Header/Title/index.tsx
versioned_docs/version-1.x/docs/recipes/configure-connectors/configure-email-connector.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/configure-sms-connector.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/configure-social-connector.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/custom-social-connector-with-standard-protocols.md
versioned_docs/version-1.x/docs/recipes/create-your-connector/connector-file-structure.mdx
versioned_docs/version-1.x/docs/recipes/create-your-connector/connector-implementation-guide.mdx
versioned_docs/version-1.x/docs/recipes/interact-with-management-api/README.md
versioned_docs/version-1.x/docs/tutorials/get-started/explore-management-api.md

- try to fix sitemap issue by adopting https://github.com/facebook/docusaurus/issues/2134#issuecomment-858475670
- redirect to the new blog address before completely remove the component
```
http://localhost:3000/blog/releases/2023-feb-extended?foo=bar&bar=baz
```
redirects to
```
https://blog.logto.io/releases/2023-feb-extended/?foo=bar&bar=baz
```

refactor: redirect to the new blog url

---

docs/docs/recipes/webhooks/webhook-request.md

Remove message id from webhook docs.
Related PR: https://github.com/logto-io/logto/pull/3979

docs: remove message id from webhook docs

---

docs/docs/recipes/integrate-logto/express/_init_client.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/express/_init_client.mdx

The "maxAge" in express integration tutorial should be in miliseconds.

fix: the express cookie maxage should be in miliseconds

---

docs/docs/fragments/_cloud_only_notification.mdx
docs/docs/recipes/custom-domain/README.mdx
docs/docs/recipes/tenant-type/README.mdx
src/components/Availability/index.tsx

docs: polish tenant type docs

---

docs/docs/recipes/protect-your-api/fragments/_token_extract.mdx
docs/docs/recipes/protect-your-api/node.mdx
versioned_docs/version-1.x/docs/recipes/protect-your-api/fragments/_token_extract.mdx
versioned_docs/version-1.x/docs/recipes/protect-your-api/node.mdx

Just fix some simple code error for API protection docs with node(express).
**Note**
The code 
```js
throw new Error({ code: 'auth.authorization_header_missing', status: 401 });
```
will result in a typescript warning:
From what I can see in the [core repo](https://github.com/logto-io/logto/blob/7c09ac850f9d9edabee67bc0d44c991a0d54d0c4/packages/core/src/middleware/koa-auth/index.ts#L30-L44), the code has been improved and get rid of the TypeScript error.
Not sure whether you guys would fix this typescript warning in docs code snippet.

docs: fix code error for API protection with node(express)

---

docs/docs/references/core/configuration.md
versioned_docs/version-1.x/docs/references/core/configuration.md

add case sensitive username env for https://github.com/logto-io/logto/pull/5170

docs: add case sensitive username env

---

tutorial/build-with-logto/_integrate-sdk-php.mdx
tutorial/build-with-logto/_integrate-sdk-python.mdx
tutorial/build-with-logto/fragments/_intro.mdx
tutorial/build-with-logto/generate.js

1. Add Python/PHP tutorial template.
2. Fix the unexpected newlines in the tutorial template "_intro.mdx".
Before:
Now:

docs: add python/php tutorial template

---

docs/sdk/fragments/_get-user-info-apis.mdx
docs/sdk/fragments/_scopes-and-claims.mdx
docs/sdk/native/android/README.mdx
docs/sdk/native/android/scopes-and-claims/_scopes-and-claims.mdx
docs/sdk/native/flutter/README.mdx
docs/sdk/native/flutter/_get-user-info.mdx
docs/sdk/spa/react/README.mdx
docs/sdk/spa/vue/README.mdx
docs/sdk/web/express/_scopes-and-claims.mdx
docs/sdk/web/go/README.mdx
docs/sdk/web/go/scopes-and-claims/_scopes-and-claims.mdx
docs/sdk/web/php/README.mdx
docs/sdk/web/php/_implement-sign-in-route.mdx
docs/sdk/web/php/scopes-and-claims/_scopes-and-claims.mdx
docs/sdk/web/python/README.mdx
docs/sdk/web/python/_implement-sign-in-route.mdx
docs/sdk/web/python/scopes-and-claims/_scopes-and-claims.mdx

Split the original "Scopes and claims" section into to"Get user info APIs" and  "Scopes and claims" and update some "scopes and claims" section to "Get user information"
Go through all SDK pages and everything work well.

refactor: reorg get user information section

---

docs/sdk/native/expo/_integration.mdx
docs/sdk/spa/angular/_integration.mdx
docs/sdk/web/nuxt/_integration.mdx

docs: polish content

---

docs/sdk/spa/vanilla-js/README.mdx
docs/sdk/web/sveltekit/README.mdx

Correct invalid get-started page links.
Related issue: https://github.com/logto-io/logto/issues/5633

fix: correct invalid get-started page links

---

docs/docs/recipes/protect-your-api/node.mdx

Correct the url param for `createRemoteJWKSet` since the url param should be an URL object.

fix(docs): use URL object for `createRemoteJWKSet`

---

docs/docs/recipes/organizations/configuration.mdx

docs: update configuration doc

---

docs/docs/recipes/organizations/integration.mdx

docs: add token guide for org api resource

---

docs/docs/recipes/organizations/understand-how-it-works.mdx

docs: update understand-how-it-works

docs: update understand-how-it-works

---

docs/docs/recipes/custom-domain/configure-custom-domain-in-console.md
docs/docs/recipes/custom-domain/use-custom-domain.md

Reorg troubleshooting section for custom domain, it is better to be in "Configure custom domain in Console".

fix: reorg domain troubleshooting

---

docusaurus.config.js
package.json
pnpm-lock.yaml

Redirect legacy `/sdk` url access to the new `/quick-start` page

chore: redirect legacy sdk urls to quick start

---

docs/quick-starts/framework/flutter/_integration.mdx
docs/quick-starts/framework/flutter/_tip.md

Fix dark SDK package name, which was replaced mistakenly when refactoring the "Quick starts" page

fix: dart sdk package name

---

docusaurus.config.js

Add old link redirect for configure mfa page

fix: add old link redirect for configure mfa page

---

.github/workflows/deploy.yml
.github/workflows/main.yml

We're using pnpm v9 in this project, but in CI, the default pnpm version in `silverhand-io/actions-node-pnpm-run-steps@v4` is v8, so the project's lockfile is not compatible in CI, and this cause the build process to fail.

fix(ci): use correct pnpm version in building process

---

docs/quick-starts/framework/expo/README.mdx
docs/quick-starts/framework/expo/api-resources/_config-api-resources.mdx
docs/quick-starts/framework/expo/api-resources/_fetch-access-token-for-api-resources.mdx
docs/quick-starts/framework/expo/api-resources/_fetch-organization-token-for-user.mdx
docs/quick-starts/framework/expo/api-resources/_index.mdx
docs/quick-starts/framework/expo/api-resources/code/_config-organization-code.md
docs/quick-starts/framework/expo/api-resources/code/_config-resources-code.md
docs/quick-starts/framework/expo/api-resources/code/_config-resources-with-scopes-code.md
docs/quick-starts/framework/expo/api-resources/code/_config-resources-with-shared-scopes-code.md
docs/quick-starts/framework/expo/api-resources/code/_get-access-token-code.md
docs/quick-starts/framework/expo/api-resources/code/_get-organization-access-token-code.md
docs/quick-starts/framework/expo/get-user-information/_index.mdx
docs/quick-starts/framework/expo/get-user-information/_scopes-and-claims-code.mdx

Fix the Expo SDK sample code. 
Previously, our Expo SDK guide referenced the get-user-information and API-resources sections directly from the React SDK, with all sample code using @logto/react. This pull request updates the guide by forking these sections and modifying the sample code to import methods from @logto/rn instead.

fix(docs): fix expo SDK sample code

---

docs/docs/recipes/migrations/README.mdx

Fix field key name for user migration, it should be `passwordDigest`.

fix: fix field key name for user migration

---

docs/quick-starts/generic/machine-to-machine/fragments/_access-logto-management-api-using-access-token.mdx
docs/quick-starts/generic/machine-to-machine/fragments/_fetch-access-token-for-logto-management-api.mdx

the original inline comments do not work

refactor: fix curl samples

---

docs/docs/recipes/logto-as-idp/README.mdx
docs/docs/recipes/logto-as-idp/configure-3rd-party-app-in-console.mdx
docs/docs/recipes/logto-as-idp/fragments/_configure-3rd-party-app.mdx
docs/integrations/third-party/oidc/README.mdx

The title is missing from the [IdP doc recipe](https://docs.logto.io/docs/recipes/logto-as-idp/configure-3rd-party-app-in-console/).
Need to refactor the re-usable "configure third-party application in Console" fragment, and set the title separately from the caller components.
Local testing results:
- From docs recipe:
- From connector integrations guide:

refactor: update title in 3rd party app config guide

---

docs/docs/recipes/impersonation/README.mdx

Fix a typo `soken` to `token` in chapter `Recipes - User impersonation`

fix: typo `soken` => `token`

---

docs/quick-starts/framework/next-auth/_config-provider.mdx

feat: next auth v5

---

docs/docs/recipes/configure-connectors/create-your-connector/connector-implementation-guide.mdx

Update build connector command in the connector implementation guide, since it has been changed by https://github.com/logto-io/logto/pull/5526/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R18

fix(docs): update build connector command in connector implementation guide

---

docs/docs/references/applications/README.mdx
docs/docs/references/connectors/README.mdx
docs/docs/references/core/README.mdx
docs/docs/references/core/_category_.json
docs/docs/references/resources/README.md
docs/docs/references/sdk-convention/README.md
docs/docs/references/translate-cli/README.mdx
docs/docs/references/users/README.md

Add new documentation for `@logto/translate` cli

feat: add docs for the new logto translate cli

---

docusaurus.config.js

Add new `Experience API` and `Management API` openapi docs link. 
Keep the top-level nav bar's API link pointing to `openapi.logto.io`, which uses the original `swagger.json` as the data source and includes all Logto APIs.
Add two new submenu items:
Experience API: `experience.openapi.json`
Management API: `management.openapi.json`

feat: add experience api doc link

---

docs/docs/references/openid-connect/authentication-parameters/README.md

update `first_screen` content in auth params doc

feat(docs): update `first_screen` content in auth params doc

---

docs/docs/references/applications/README.mdx
docs/docs/references/openid-connect/backchannel-logout/README.md

I was reading the docs when I didn't understand some of the abbreviations. So I added brackets to the first occurrence of the terms RP and OP that I didn't understand. According to this guide for writing <https://www.mcc.gov/resources/story/section-writing-guide-good-grammar/>
Idea: a glossary of terms used in the docs

refactor: define RP and OP abbreviations with parentheses

---

tutorial/build-with-logto/_integrate-sdk-react.mdx
tutorial/build-with-logto/_integrate-sdk-vue.mdx

Remove duplicated "Implement sign-in and sign-out" section title from generated "build-with-logto" guides.

fix: remove duplicated section titles from generated docs

---

docs/quick-starts/framework/nuxt/_get-user-information.mdx
docs/quick-starts/framework/nuxt/_integration.mdx

When routing within a nuxt app, the "nuxt-link" component should always be used instead of the regular anchor tag to make sure the page isn't refreshed but is rendered using SPA.
See https://nuxt.com/docs/api/components/nuxt-link for more details.

refactor: use nuxt-link instead of anchor tag

---

docs/docs/recipes/organizations/integration.mdx

Fix organization scope value used in the integration guide.

fix(docs): organization scope value in org integration guide

---

docs/get-started/invite-team-members.mdx
docusaurus.config.ts
package.json
pnpm-lock.yaml
src/mdx-components/CloudLink/index.tsx

Add `<CloudLink>` component to support Cloud Console URL navigation.
You can use it in the following ways:
```html
<CloudLink to="applications" />
```
```html
<CloudLink to="/applications" />
```
These are equivalent to:
```md
[Applications](https://cloud.logto.io/to/applications)
```
Or specify a display text
```html
<CloudLink to="/sign-in-experience/sign-in-and-sign-out">
Sign-in Experience > Sign-in and sign-out
</CloudLink>
```

feat: add cloud console link component

---

docs/introduction/README.mdx
src/components/NavGroup/index.module.scss
src/components/NavGroup/index.tsx
src/components/Url/index.module.scss
src/components/Url/index.tsx
src/theme/DocCardList/index.tsx
src/theme/MDXComponents/index.ts

Add a new `<NavGroup />` component.
Design:
Example usage:
```
import Icon1 from '@site/src/assets/icon1.svg';
import Icon2 from '@site/src/assets/icon2.svg';
import Icon3 from '@site/src/assets/icon3.svg';
<NavGroup
label="This is a grouped nav items"
items={[
{ icon: <Icon1 />, docId: 'your-doc-id-1' },
{ icon: <Icon2 />, docId: 'your-doc-id-2' },
{ icon: <Icon3 />, docId: 'your-doc-id-3' },
]}
/>
```

feat: add NavGroup component

---

docusaurus.config.ts

e.g. https://docs.logto.io/de should have the logo points to https://logto.io/de

refactor: use locale-aware link for logo

---

src/components/Banner/index.module.scss
src/components/LanguageSwitchBanner/index.module.scss
src/components/LanguageSwitchBanner/index.tsx
src/theme/EditMetaRow/index.tsx
src/theme/EditMetaRow/styles.module.scss

Improve CSS styles of language switch banner and doc feedback component

style: improve styles of language switch banner and feedback row

---

i18n/de/code.json
i18n/es/code.json
i18n/fr/code.json
i18n/pt-BR/code.json
i18n/zh-CN/code.json
src/theme/EditMetaRow/index.tsx

Add missing i18n translation of the "Help us improve docs!" label.

fix: add missing i18n translation to the help us improve docs label

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/integrate-logto/protected-app.mdx

Fix the broken mermaid chart found in "Integrate Logto - Protected app" in zh-CN locale
Before:
After:

fix: broken mermaid chart in zh-CN translation

---

docusaurus.config.ts
src/scss/custom.scss
src/theme/CodeBlock/Content/String.tsx
src/theme/CodeBlock/Content/styles.module.css

Ref-styling code block component. Force use the `Dracula` theme for both light and dark modes.

refactor: code block component styling

---

src/scss/custom.scss
src/theme/DocItem/Layout/index.module.scss
src/theme/DocItem/Layout/index.tsx

Improve mobile page performance on initial loading
- Hide right side doc TOC on mobile, as previously it would still impact the mobile layout on init, and the page jitters when its state gets updated
Growing from:
Back to 76-86-ish

refactor: improve mobile page performance

---

i18n/de/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/end-user-flows/organization-experience/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/end-user-flows/sign-up-and-sign-in/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/end-user-flows/organization-experience/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/end-user-flows/sign-up-and-sign-in/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/end-user-flows/organization-experience/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/end-user-flows/sign-up-and-sign-in/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/end-user-flows/organization-experience/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/end-user-flows/sign-up-and-sign-in/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/end-user-flows/organization-experience/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/end-user-flows/sign-up-and-sign-in/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/end-user-flows/organization-experience/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/end-user-flows/sign-up-and-sign-in/README.mdx

Add i18n translations to the sublist labels in "End user flows" sidebar category.

chore: add i18n translation to sublist labels in end user flows

---

docusaurus.config.ts
src/theme/CodeBlock/Content/styles.module.css
src/theme/DocItem/Layout/index.module.scss
src/theme/DocItem/Layout/index.tsx

Fix a layout issue when code editor is presented in the docs.
As the code editor has `min-width: 100%`, it would take all the available horizontal space on the right side, pushing the right side TOC off the screen.
Therefore, we still need to limit the max-width of the `main` container element (which was removed by a previous PR).

fix: page layout when code editor is presented

---

src/scss/custom.scss
src/theme/Admonition/Layout/styles.module.css

Fix the styling issues for code block editors used inside admonition.

fix: code editor styles in admonitions

---

docs/connectors/connector-data-structure.mdx
docs/user-management/advanced-user-search.mdx
docs/user-management/user-data.mdx

fix: broken anchor links

---

src/scss/custom.scss

Docusaurus will apply `display: block;` to footer items on smaller screen devices, which breaks the vertical center alignment of the icon and text. This PR fixes it by overriding it with `display: inline-flex;`.
Before:
After:

fix: footer item style on mobile

---

docs/quick-starts/framework/go/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/go/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/go/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/go/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/go/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/go/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/go/README.mdx

Add missing metadata for Go SDK guide, which is used for generating "Build X with Y" properties.

fix: add missing metadata to Go SDK guide

---

docs/quick-starts/framework/next-app-router/README.mdx
docs/quick-starts/framework/next/README.mdx
docs/quick-starts/framework/next/_external-storage.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/next-app-router/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/next/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_external-storage.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/next-app-router/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/next/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_external-storage.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/next-app-router/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/next/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_external-storage.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/next-app-router/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/next/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_external-storage.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/next-app-router/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/next/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_external-storage.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/next-app-router/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/next/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_external-storage.mdx

Add Next.js external storage docs.

feat: add next.js external storage

---

src/scss/custom.scss
src/theme/Admonition/Layout/styles.module.css
src/theme/CodeBlock/Content/String.tsx
src/theme/CodeBlock/Content/styles.module.css

Fix the styles for code editor that embedded in admonitions.
Before:
After:

fix: styles for code editor embedded in admonition

---

docs/quick-starts/framework/dotnet-blazor-wasm/_for-tutorial.mdx
docs/quick-starts/framework/expo/_for-tutorial.mdx
docs/quick-starts/framework/next/_for-tutorial.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-blazor-wasm/_for-tutorial.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/_for-tutorial.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_for-tutorial.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-blazor-wasm/_for-tutorial.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/_for-tutorial.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_for-tutorial.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-blazor-wasm/_for-tutorial.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/_for-tutorial.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_for-tutorial.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-blazor-wasm/_for-tutorial.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/_for-tutorial.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_for-tutorial.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-blazor-wasm/_for-tutorial.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/_for-tutorial.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_for-tutorial.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-blazor-wasm/_for-tutorial.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/_for-tutorial.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/next/_for-tutorial.mdx

Remove redundant SDK checkpoint sections from tutorials, as the previous `<Integration />` section already included the checkpoint section.

refactor: remove redundant sdk checkpoint sections from tutorials

---

i18n/de/code.json
i18n/es/code.json
i18n/fr/code.json
i18n/ja/code.json
i18n/pt-BR/code.json
i18n/zh-CN/code.json
plugins/tutorial-generator/index.ts
plugins/tutorial-generator/utils.ts
src/components/Dropdown/index.tsx
src/hooks/use-categorized-tutorial-metadata.ts
src/theme/BlogLayout/index.tsx
src/theme/BlogPostItem/Header/SelectionDropdown/index.module.scss
src/theme/BlogPostItem/Header/SelectionDropdown/index.tsx
src/theme/BlogPostItem/Header/Title/index.tsx
src/theme/BlogPostItem/Header/Title/styles.module.css
src/theme/BlogPostItem/Header/TitleWithSelectionDropdown/index.module.scss
src/theme/BlogPostItem/Header/TitleWithSelectionDropdown/index.tsx

Add sdk and connector gude selection dropdown in the "Build X with Y" tutorial titles.

feat: add sdk and connector selection dropdown to tutorial title

---

i18n/de/code.json
i18n/es/code.json
i18n/fr/code.json
i18n/ja/code.json
i18n/pt-BR/code.json
i18n/zh-CN/code.json

refactor: sync i18n translations

---

docs/end-user-flows/account-settings/by-account-api.mdx
i18n/es/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/by-account-api.mdx
i18n/fr/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/by-account-api.mdx
i18n/ja/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/by-account-api.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/by-account-api.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/end-user-flows/account-settings/by-account-api.mdx

Fix the method of creating new identity.

fix: correct the method of linking social identities

---

docusaurus.config.ts
src/theme/BlogLayout/index.module.scss

- Keep SVG viewbox property in order to maintain the original width and height of the SVGs
- Fix the layout styles in the tutorial details page (Docusaurus blog layout)

fix: keep svg viewbox and fix tutorial layout styles

---

docs/quick-starts/framework/expo/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/expo/README.mdx

Update the ReactNative/Expo SDK integration guide.  Add the affected SDK version declaration in the troubleshooting section.

chore: update expo SDK content

---

plugins/tutorial-generator/README.md

Add README to the tutorial generator plugin, which generates "Build X with Y" tutorials

chore: add readme to the tutorial generator plugin

---

docs/quick-starts/framework/next-app-router/_integration.mdx

Typo fix
Typo fix. Fixed spelling of the word "home".

fix: typo in next app router integration guide

---

docusaurus.config.ts
static/_redirects

Disable "Build X with Y" tutorial generation for unsupported locales: `de, ko, pt-BR, zh-CN, zh-TW`.
This config change will completely disable the "blog" plugin for tutorial generations for the locales above, freeing up about **"7k"** files in the production build folder.

refactor: disable tutorial generation for unsupported locales

---

.github/workflows/main.yml

Remove "outdated translation" detection from the main GitHub action workflow, since we now have a new workflow to automate the process.

chore: remove outdated translation detection from main workflow

---

.github/workflows/content-generation.yml

Change the "content generation" CI workflow concunrrency group to repository level, in order to make it cancellable when a new commit comes into master branch.

fix: content generation workflow concurrency group

---

.github/workflows/content-generation.yml

- In the "Content generation" action workflow, check if the previous steps have made file changes before submitting a PR.
- Also unified the concurrency group name pattern with the other workflows.

fix: check if previous CI steps has made file changes before submitting PR

---

.github/workflows/content-generation.yml

Fix the wrongly configured branch name in the "submit PR" step in "content generation" workflow

fix: wrong branch name used in content generation workflow

---

docs/integrations/social/x/README.mdx

Update Twitter guide `tutorial_name` to remove the parenthesis from generated tutorial slugs

chore: update twitter tutorial name to remove parenthesis from generated tutorial slugs

---

.github/workflows/content-generation.yml

Move `translate` before `write-heading-ids`, in order to make sure that newly created i18n translation files can also have heading IDs synced with EN version.

fix: move translate before write heading ID in workflow

---

write-heading-ids.mjs

Force sync heading IDs in the i18n translations with the original English version docs

refactor: force sync heading IDs of i18n translation with EN docs

---

.github/workflows/main.yml

Use matrix strategy split up the building of i18n builds, in order to speedup the overall running time of the mandatory CI checks in docs.
Currently the average building time is around 30 minutes for 9 locales. After the optimization, it is expected to be around 3-4 minutes.

refactor: reduce running time of mandatory CI checks

---

write-heading-ids.mjs

Update `write-heading-ids.mjs` script to handle a potential unexpected backslash in the regex matching group

fix: update regex matching rules in write-heading-ids script

---

i18n/de/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/ko/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/feishu-web/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx

Find and replace some incorrect heading IDs generated by the older version of `write-heading-ids.mjs` script. The new version script has addressed this issue (#1038).

fix: incorrect heading ids generated by an older version of script

---

docs/end-user-flows/sign-up-and-sign-in/README.mdx

align the naming convention of the experience app

fix: align the naming convention of experience app

---

translate.shared.mjs

Change the Git file datetime format to unix timestamp, in order to fix unstable comparison results in the CI workflow.
Previously the output format is like: `2024-12-17 08:26:38 +0000`, and the string comparison might not be stable.

fix: git file timestamp comparison

---

.github/workflows/content-generation.yml
translate.shared.mjs

Fix the issue that when translating files in CI environment, the script fails to detect the correct target files by comparing the git commit history.
The issue is caused by the default shallow fetch behavior of the `actions/checkout` plugin. Therefore, the commit history are all set to the current system timestamp, instead of the real file commit timestamps.
This PR fixes the issue by setting `fetch-depth=0` so that the full commit history can be fetched.

fix: git history comparison in translate script

---

.github/workflows/content-generation.yml

We should continue the "content generation" workflow on error, so that even if the AI generated translation is problematic on "build" or "lint" process later on, we can still collect the intermediate file changes and create the PR regardless.
Then we can manually fix the trivial issues ourselves without needing to re-run the whole process, since most of the translation results would be good. By doing this, we can actualy saving unnecessary extra AI token costs.

refactor: continue the content generation workflow on error

---

terms/custom.scss

The top navbar is missing in all docs pages, which was caused by a CSS pollution in the blog custom css file.

fix: top navbar should be rendered in docs pages

---

docs/logto-cloud/custom-domain.mdx

We recently had issues with our certificate not being renewed and had to add pki.goog to our CAA records (we already had letsencrypt.org). The information for this was found from [Google's docs](https://cloud.google.com/load-balancing/docs/ssl-certificates/google-managed-certs#caa) and based on the fact that the existing certificate was issue by Google. Adding these records fixed the certificate issues for us, so I think these are the correct CAA records.

docs: add required CAA records to cert troubleshooting answer

---

docs/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx
i18n/de/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx
i18n/es/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx
i18n/fr/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx
i18n/ja/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx
i18n/ko/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_add-validation-logic.mdx

Fix the wrong openid configuration URL in .NET docs. (fixes #1175)

docs: fix the wrong openid configuration url

---

src/theme/MDXComponents/Table/index.tsx

Fixed the page crash when opening doc pages that contain table components.
```
The full text of the error you just encountered is:
An unknown Component is an async Client Component. Only Server Components can be async at the moment. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.
```

fix: react minified error 482 on doc pages that have table component

---

docs/logto-cloud/README.mdx
docs/logto-cloud/dev-tenant-data-retention.mdx
docs/logto-cloud/tenant-settings.mdx

- Introduced a new documentation page for the 90-day user data retention policy in dev tenants.
- Updated tenant settings documentation to reference the new policy and clarify that only users, not organizations, are deleted after 90 days

docs: add dev tenant data retention policy

---

docs/logto-oss/deployment-and-configuration.mdx

Introduce a section for configuring a PostgreSQL database for Logto, including user creation, permissions, and schema setup. This addition also highlights using a batch job for schema initialization and specifies best practices for Docker image versioning and permissions.

feat: database setup instructions to oss deployment docs

---

i18n/es/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/go/_init.mdx
i18n/es/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/rust/_init.mdx
i18n/fr/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/rust/_init.mdx
i18n/ja/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/rust/_init.mdx
i18n/ko/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/python/fragments/django-rest/_validation.md
i18n/pt-BR/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/rust/_init.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/go/_init.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/dotnet/_init.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/rust/_init.mdx
translate.openai.mjs

Updated multiple internationalized documentation files to remove inline translations from programming language code identifiers, class names, and error types. Now only comments and output messages remain translated.
Also updated openai prompt, telling it not to translate code examples in fenced code blocks.

fix: remove unexpected translations from code identifiers in i18n docs
