logto-io/docs

.github/workflows/commitlint.yml
.github/workflows/main.yml
.husky/commit-msg
.husky/pre-commit
commitlint.config.js
docs/docs/recipes/integrate-logto/components/AppNote.tsx
docs/docs/recipes/integrate-logto/components/SignInNote.tsx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/components/AppNote.tsx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/components/SignInNote.tsx
lint-staged.config.js
package.json
pnpm-lock.yaml
src/components/Columns/index.tsx
src/include.d/react-app.d.ts
src/theme/Footer/FooterLayout.tsx
src/theme/Footer/index.d.ts
src/theme/Footer/index.tsx
tsconfig.json

chore: add lint

---

docs/docs/tutorials/get-started/check-out-demo.md
docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx

polish the content to make it clear for what to do next in the get started tutorial

docs(en-US): polish get started content

---

docs/docs/tutorials/get-started/README.md
docs/docs/tutorials/get-started/add-a-social-connector.md
docs/docs/tutorials/get-started/check-out-demo.md
docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx
docs/docs/tutorials/get-started/customize-sign-in-experience.md

add the English version of "Customize SIE" and minor content improvements.

docs(en-US): customize SIE

---

docs/docs/recipes/create-your-connector/README.md
docs/docs/recipes/create-your-connector/_category_.json
docs/docs/recipes/customize-sie/README.md
docs/docs/recipes/customize-sie/_category_.json
docs/docs/recipes/customize-sie/configure-branding-and-exp.md
docs/docs/recipes/customize-sie/configure-sign-in-methods.md
docs/docs/recipes/customize-sie/set-language-display.md
docs/docs/recipes/integrate-logto/README.md
docs/docs/references/connectors/README.md
docs/docs/tutorials/get-started/_connectors-intro.md
docs/docs/tutorials/get-started/add-a-social-connector.md
docs/docs/tutorials/get-started/customize-sign-in-experience.md
docs/docs/tutorials/get-started/enable-passcode-sign-in.md
docs/docs/tutorials/get-started/enable-passcode-sign-in.mdx
docs/docs/tutorials/get-started/enable-social-sign-in.md
src/components/Columns/index.module.scss
src/components/Columns/index.tsx
src/theme/Footer/FooterLayout.tsx
tsconfig.json

- Enable SMS or email passcode sign-in
- Add doc hierarchy accordingly

docs(en-US): enable SMS or email passcode sign-in

---

docs/docs/README.md

docs(en-US): update intro

---

.github/workflows/deploy.yml
docusaurus.config.js

chore: add CD

---

docs/docs/recipes/configure-connectors/README.md
docs/docs/recipes/customize-sie/README.md
docs/docs/recipes/customize-sie/configure-branding-and-exp.md
docs/docs/recipes/customize-sie/configure-branding.mdx
docs/docs/recipes/customize-sie/fragments/_dark-mode-note.md
docs/docs/recipes/customize-sie/set-language-display.md
docs/docs/recipes/customize-sie/tou-and-language.md
docs/docs/recipes/deployment/README.md
docs/docs/recipes/localization/README.md
docs/docs/recipes/manage-users/README.md
docs/docs/recipes/protect-your-api/README.md
docs/docs/tutorials/get-started/customize-sign-in-experience.mdx
docs/docs/tutorials/get-started/further-readings.md

- README of SIE recipe 
- branding recipe
- manual recipe positioning
- refine content to align with the latest

docs(en-US): sie branding

---

docs/docs/recipes/customize-sie/tou-and-language.md
docs/docs/recipes/customize-sie/tou-and-language.mdx

docs(en-US): terms of use and language

---

docs/docs/recipes/customize-sie/README.md
docs/docs/recipes/customize-sie/configure-branding.mdx
docs/docs/recipes/customize-sie/configure-sign-in-methods.md
docs/docs/recipes/customize-sie/configure-sign-in-methods.mdx
docs/docs/recipes/customize-sie/fragments/_save-changes.md
docs/docs/recipes/customize-sie/tou-and-language.md
docs/docs/recipes/customize-sie/tou-and-language.mdx
docs/docs/tutorials/get-started/enable-passcode-sign-in.mdx
docs/docs/tutorials/get-started/enable-social-sign-in.mdx
docs/docs/tutorials/get-started/further-readings.md

introduce the concept of sign-in methods and explain in details

docs(en-US): configure sign-in methods

---

docs/docs/references/core/README.md

introduction of Logto core service

docs(en-US): core intro

---

docs/docs/recipes/localization/README.md

docs(en-US): temp l10n

---

.vscode/settings.json
docs/docs/README.md

- promote Docker Compose to the first installation method
- polish content

docs(en-US): optimize global intro

---

docs/docs/references/core/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/README.md

- polish zh-CN global intro
- reference: core -> core service

docs: polish content

---

docs/docs/recipes/manage-users/README.md
docs/docs/recipes/manage-users/_category_.json
docs/docs/recipes/manage-users/by-logto-core-management-api.md
docs/docs/recipes/manage-users/on-admin-console-page.md
docs/docs/recipes/manage-users/on-storage.md

Initialize the structure of Manage Users docs
- Sidebar
- README

docs(en-US): init Manage Users docs structure

---

docs/docs/recipes/localization/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-passcode-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-social-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/further-readings.md

polish content per previous reviews

docs(zh-CN): polish content

---

docs/docs/references/core/configuration.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/core/configuration.md

docs(zh-CN): core configuration

---

src/scss/custom.scss

380px to make they'll in one line

refactor: tweak sidebar width

---

docs/docs/fragments/_application_types_intro.mdx
docs/docs/references/applications/README.mdx
docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx

docs(en-US): applications reference

---

docs/docs/recipes/integrate-logto/ios.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/components/AppNote.tsx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/components/SignInNote.tsx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/ios.mdx

docs(zh-CN): iOS integration guide

---

docs/docs/recipes/integrate-logto/android.mdx
docs/docs/recipes/integrate-logto/ios.mdx
docs/docs/recipes/integrate-logto/react.mdx
docs/docs/recipes/integrate-logto/traditional.mdx
docs/docs/recipes/integrate-logto/vue.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/android.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/react.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/vue.mdx

polish integration guide titles

docs: polish titles

---

docs/docs/recipes/manage-users/README.md
docs/docs/recipes/manage-users/by-logto-core-management-api.md
docs/docs/recipes/manage-users/by-management-api.md

Add the summary in the Manage Users readme.

docs(en-US): add Manage Users summary

---

.github/workflows/deploy.yml

use org-level bot PAT for deployment

ci: use organization bot token

---

docs/docs/recipes/manage-users/README.md
docs/docs/recipes/manage-users/by-management-api.md
docs/docs/recipes/manage-users/using-admin-console.md

Add user on Admin Console page

docs(en-US): add user on AC page

---

docs/docs/recipes/manage-users/using-admin-console.md
docs/docs/recipes/manage-users/using-management-api.md

Refine sidebar labels of Manage users

docs(en-US): refine sidebar labels of Manage users

---

docs/docs/recipes/integrate-logto/fragments/_configure-redirect-uri.mdx
docs/docs/recipes/integrate-logto/fragments/_web-sign-in-flow-summary.mdx
docs/docs/recipes/integrate-logto/ios.mdx
docs/docs/recipes/integrate-logto/vanilla-js.mdx

see caution
https://docusaurus.io/docs/markdown-features/react#importing-markdown

refactor(en-US): fixing table of contents

---

docs/docs/recipes/integrate-logto/fragments/_further-readings.md
docs/docs/recipes/integrate-logto/fragments/_web-assuming-url.md
docs/docs/recipes/integrate-logto/ios.mdx
docs/docs/recipes/integrate-logto/react.mdx
docs/docs/recipes/integrate-logto/traditional.mdx
docs/docs/recipes/integrate-logto/vanilla-js.mdx
docs/docs/recipes/integrate-logto/vue.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/traditional.mdx

- align react guide styles with vanilla js
- extract common further readings component

docs(en-US): react integration guide

---

docs/docs/recipes/integrate-logto/android.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/android.mdx

Remove redundant contents of the guide.

docs: update android integration guide

---

docs/docs/recipes/integrate-logto/vue.mdx

Aligned guide styles with React

refactor(en-US): vue integration guide

---

docs/docs/recipes/manage-users/using-management-api.md

Manage users using Management API

docs(en-US): manage users using management api

---

docs/docs/recipes/manage-users/using-admin-console.md
docs/docs/references/users/README.md

- View and update user profile
- View user activities
- Delete user
- Reset user password

docs(en-US): manage users using ac

---

docs/docs/recipes/integrate-logto/react.mdx
docs/docs/recipes/integrate-logto/vue.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/react.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/vanilla-js.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/vue.mdx

Aligned guide styles with React zh-CN

refactor(zh-CN): vue integration guide

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

docs: update docker compose script

---

docs/docs/recipes/integrate-logto/fragments/_web-assuming-url.md
docs/docs/recipes/integrate-logto/traditional.mdx
docs/docs/recipes/integrate-logto/vue.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/android.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/react.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/vanilla-js.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/vue.mdx

Some minor updates on the wording and sample code in react and vue recipes

refactor: minor updates on react and vue recipes

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

docs(zh-CN): update get started

---

docs/docs/references/users/README.md

References -> Users -> Profile

docs(en-US): references -> users -> profile

---

docusaurus.config.js

- link navbar logo to official website
- make edit link locale-aware

refactor: update links

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/android.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/ios.mdx

polish logto integration guide titles

docs(zh-CN): polish tutorial title

---

docs/docs/recipes/integrate-logto/android.mdx
docs/docs/recipes/integrate-logto/vanilla-js.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/android.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/ios.mdx

refactor: improve several minor issues in sdk integration recipes

---

docs/docs/recipes/integrate-logto/traditional.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/traditional.mdx

docs(zh-CN): 传统 Web 应用

---

docs/docs/references/users/README.md

References -> User profile -> Identities

docs(en-US): references -> user profile -> identities

---

docs/docs/recipes/integrate-logto/traditional.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/traditional.mdx

Typo fixes and other minor adjustments

fix: minor issues in traditional web tutorial

---

docs/docs/recipes/integrate-logto/traditional.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/traditional.mdx

Sync changes back to docs, as per @darcyYe 's review comments

refactor: sync changes from ac back to docs

---

docs/docs/recipes/manage-users/using-management-api.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/manage-users/using-management-api.md

Add the zh-CN version of Manage users using Management API

docs(zh-CN): add Manage users using Management API

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

update docker tag and add comments

docs: use prerelease tag for docker image

---

docs/docs/tutorials/get-started/README.mdx

docs(en-US): fix tag

---

docs/docs/recipes/manage-users/integrate-logto-data.md

A short production tip on how to identify user.

docs(en-US): identify user reference

---

docs/docs/recipes/protect-your-api/README.md

Add server-side validation instruction for the API protection.
@logto-io/eng

docs(api protection): add server side validation

---

docs/docs/recipes/manage-users/integrate-logto-data.md

Integrate with logto user data

docs(en-US): integrate with logto user data

---

docs/docs/recipes/protect-your-api/README.md
docs/docs/recipes/protect-your-api/fragments/_secret_key.md
docs/docs/recipes/protect-your-api/fragments/_token_extract.mdx
docs/docs/recipes/protect-your-api/fragments/_token_validation.mdx

add java sample code and create some fragments to reduce line size. 
@eng

docs(api protection): add java sample code

---

docs/docs/recipes/protect-your-api/README.md
docs/docs/recipes/protect-your-api/fragments/_secret_key.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/fragments/_secret_key.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/fragments/_token_extract.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/fragments/_token_validation.mdx

add protect your api zh-CN doc.
@logto-io/eng

docs(zh-CN): add protect api zh-CN

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/manage-users/integrate-logto-data.md

docs(zh-CN): identify user

---

docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx
docs/docs/tutorials/get-started/enable-passcode-sign-in.mdx
docs/docs/tutorials/get-started/enable-social-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-passcode-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-social-sign-in.mdx
src/components/Columns/index.tsx

add the missing links for integration and connectors

docs: add links

---

docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx
docs/docs/tutorials/get-started/enable-passcode-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-passcode-sign-in.mdx

docs: fix typo

---

docs/docs/tutorials/get-started/README.mdx

add the missing "click here" link

docs(en-US): add missing link

---

docs/docs/recipes/integrate-logto/android.mdx
docs/docs/recipes/integrate-logto/fragments/_android_sdk_setup_code_java.md
docs/docs/recipes/integrate-logto/fragments/_android_sdk_setup_code_kotlin.md
docs/docs/recipes/protect-your-api/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/android.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/fragments/_android_sdk_setup_code_java.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/fragments/_android_sdk_setup_code_kotlin.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/README.md

- update android SDK setup code
- share android SDK setup code with the _Protect Your API_ doc.

docs: update android sdk setup code

---

docs/docs/recipes/integrate-logto/ios.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/ios.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/README.md

docs: update iOS tutorial

---

docs/docs/recipes/manage-users/using-admin-console.md

```markdown
- **From application**: The name of the application that the user initially registered with.
```

docs(en-US): refine Manage users using AC

---

docs/docs/references/users/README.md

Remove the duplicate sentence after resolving conflicts

fix(en-US): remove duplicate sentence after resolving conflicts 

---

docs/docs/tutorials/get-started/README.mdx

remove `/welcome` to align with zh-CN docs

chore: update get started

---

docs/docs/references/resources/fragments/_api_resource_schema.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/resources/fragments/_api_resource_schema.mdx

adjust accesstoken default TTLin doc  accordingly. 
related PR: https://github.com/logto-io/logto/pull/1430
@logto-io/eng

docs(zh-CN, en-US): adjust accesstoken default ttl accordingly

---

docusaurus.config.js

chore: add plausible

---

babel.config.js
package.json
pnpm-lock.yaml
src/components/Columns/index.tsx
src/pages/Api/index.tsx
src/theme/Footer/FooterLayout.tsx
src/theme/Footer/LinkItem.tsx
src/theme/Footer/index.tsx

upgrade and adopt the latest configs

chore: upgrade configs

---

.github/workflows/main.yml

update the yml to trigger workflow correctly
after merge

ci: update main.yml

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/fragments/_connectors-wip.md

docs(zh-CN): fix link in connectors doc

---

docs/docs/recipes/manage-users/you-dont-need-a-user-table.md

docs(en-US): fix typo in 'You dont need a user table'

---

docs/docs/tutorials/get-started/README.mdx

fix format issue in `<summary>` component
locally

docs(en-US): fix typo in get started

---

docs/docs/tutorials/get-started/enable-social-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-social-sign-in.mdx

Update Wechat connector package old url to new.

docs: update wechat connector package url

---

docs/docs/tutorials/get-started/enable-social-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-social-sign-in.mdx

Fix alipay web connector link.

docs: fix alipay web connector link

---

docs/sdk/JavaScript/next/classes/default.md

update Next.js reference, since the method "handleAuthRoutes" is just added.
Local preview.

docs: update js-next reference

---

docs/docs/recipes/configure-connectors/connector-setup-tips.md
docs/docs/recipes/create-your-connector/fragments/_index_contents.md
docs/docs/references/connectors/fragments/_connector_storage_intro.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/configure-connectors/connector-setup-tips.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/create-your-connector/fragments/_index_contents.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/connectors/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/connectors/fragments/_connector_storage_intro.mdx

Update links in connector-related docs (using relative paths with file extension).
tested locally.

docs(connector): update connector related docs links

---

docs/docs/references/core/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/core/README.mdx

fix core and convention links
links work as expected

fix: ref links

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

Mention `X-Forward-Proto` in quick troubleshooting section.

docs: mention X-Forward-Proto in quick troubleshooting section

---

docs/docs/recipes/deployment/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/deployment/README.md

docs(zh-CN): deployment

---

docs/docs/recipes/deployment/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/deployment/README.md

accidentally resolved comment without disabling auto-merge in #206, fix it
N/A

docs: add endpoint sample in deployment

---

docusaurus.config.js

followed https://docusaurus.io/docs/search#using-algolia-docsearch
safe to commit API key
works locally

feat: add search

---

docusaurus.config.js

due to permission issues, re-generated the old one.
N/A

feat: change api key

---

tsconfig.json

Simplify `tsconfig.json`
- Remove the unnecessary `/` and `./`
Pass CI

refactor: simplify tsconfig.json

---

docs/docs/recipes/integrate-logto/README.md
docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx

add nextjs links to intro articles.
Local preview

docs: add nextjs links

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

chore: add DockerHub image info

---

docs/docs/tutorials/get-started/README.mdx

Update wording: use `proxy config` instead of `server config` to avoid confusion.
N/A

chore: update wording to avoid confusion

---

docs/docs/recipes/protect-your-api/fragments/_token_extract.mdx
docs/docs/recipes/protect-your-api/fragments/_token_validation.mdx

add python api protection code
test locally
@logto-io/eng

chore(docs): add python api protection code

---

docs/docs/recipes/integrate-logto/express.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/express.mdx

Add express integrate guide.
Note: zh-CN file is a placeholder.
Local previewed.

docs: add express integrate guide

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/express.mdx

add express integration guide
Local preview

docs(zh-CN): add express integration guide

---

docs/docs/recipes/integrate-logto/fragments/_spring-boot-gradle-build.md
docs/docs/recipes/integrate-logto/fragments/_spring-boot-home-controller.md
docs/docs/recipes/integrate-logto/fragments/_spring-boot-home-page.md
docs/docs/recipes/integrate-logto/fragments/_spring-boot-login-configuration.md
docs/docs/recipes/integrate-logto/fragments/_spring-security-configuration.md
docs/docs/recipes/integrate-logto/spring-boot.mdx

Extract the code blocks from `spring-boot.mdx` to `fragments/_spring-*.md` to avoid becoming too long (before adding the sign-out, profile, and protected resource parts).
Locally previewed and tested.

refactor(docs): extract code blocks from spring-boot.mdx

---

docs/docs/recipes/protect-your-api/_category_.json
docs/docs/recipes/protect-your-api/spring-boot.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/_category_.json
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/spring-boot.mdx

Protect your API on Spring Boot (as a resource server)
- Provide audience validator
- Configure Spring Security
- Access protected API
- Locally previewed the doc.
- Locally tested the sample code.

docs(en-US): protect your API on Spring Boot

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/spring-boot.mdx

The zh-CN version of Protect your API on Spring Boot.
- Locally previewed and tested.

docs(zh-CN): protect your API on Spring Boot

---

docs/docs/references/sdk-convention/fragments/_core_functions.md

change the `scopes` param type  of `fetchTokenByRefreshToken` to `string[]`
Test locally.

docs: update sdk convention about `fetchTokenByRefreshToken`

---

docs/docs/recipes/protect-your-api/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/spring-boot.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/resources/README.md

Fix typos in Protect your API and Spring Boot
Locally previewed.

fix(docs): fix typos in Protect your API

---

docs/docs/recipes/integrate-logto/fragments/_further-readings.md
docs/docs/recipes/protect-your-api/README.mdx
docs/docs/recipes/protect-your-api/spring-boot.mdx
docs/docs/references/resources/README.md
docs/docs/tutorials/get-started/further-readings.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/fragments/_further-readings.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/spring-boot.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/resources/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/further-readings.md

Change `protect-your-api/README` file extension from `.md` to `.mdx` and update related links.
Locally previewed and tested.

refactor(docs): change protect-your-api/README file extension from .md to .mdx

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

Warn the users that they should never use our docker compose command in prod env, as they might end up losing data when re-executing the command.

docs: warn the users that using docker compose in prod env will lose data

---

docs/docs/recipes/deployment/README.md
docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/deployment/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

Add `docker run` and nginx reverse proxy samples, as these are the most often asked questions in community.

docs: add docker command and reverse proxy sample

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/go-web.mdx

docs: update go web integration guide (zh-CN)
Test locally.

docs: update go web integration guide (zh-CN)

---

docs/docs/recipes/integrate-logto/README.md
docs/docs/recipes/integrate-logto/go-web.mdx

Split the SDK docs directory
- spa
- traditional
- native
- backend
test locally
@logto-io/eng

refactor(docs): split the SDK docs directory

---

docs/docs/recipes/protect-your-api/spring-boot.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/spring-boot.mdx

Describe how to get `issuer` and `jwks_uri` in the doc "Protect your API on Spring Boot"
Locally tested and previewed.

docs(en-US,zh-CN): describe how to get issuer and jwks_uri

---

docs/docs/recipes/integrate-logto/go-web.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/go-web.mdx

docs: remove `persistAccessToken` from go web docs
Test locally.

docs: remove `persistAccessToken` from go web docs

---

docs/docs/references/sdk-convention/fragments/_platform_basic_types.md

Limit `usingPersistStorage` to iOS, Android, SPA, and other client SDKs.
Test locally.

docs: update the `usingPersistStorage` definition in the SDK convention

---

docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx

Fixed a typo ("Tranditional" to "Traditional")
I didn't test it, as it's just a documentation fix.
Thank you for your time.

fix(doc): fix typo

---

docs/docs/references/core/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/core/README.mdx

update doc per core update
N/A

fix: me api

---

docs/docs/recipes/protect-your-api/node.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/node.mdx

docs: add missing space

---

docs/docs/recipes/deployment/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/deployment/README.md

Add simple description on how to run database migration
Local previewed

docs: db migration

---

docs/docs/recipes/deployment/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/deployment/README.md

Add docs on containerization, docker/kubernetes.
Local preview.

docs: containerization

---

docs/docs/recipes/integrate-logto/express.mdx
docs/docs/recipes/integrate-logto/next-js.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/express.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/next-js.mdx

Add docs on the config "fetchUserInfo" in `next` and `express`.
Local preview.

docs: fetchUserInfo for express and next

---

docs/docs/tutorials/get-started/enable-passcode-sign-in.mdx
docs/docs/tutorials/get-started/enable-social-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-passcode-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-social-sign-in.mdx

docs: update connector list

---

docs/docs/recipes/integrate-logto/go-web.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/go-web.mdx

docs: add fetch user info content to the Go SDK integration guide
Test locally.

docs: add fetch user info content to the Go SDK integration guide

---

docs/docs/recipes/integrate-logto/android.mdx
docs/docs/recipes/integrate-logto/fragments/_fetch-user-information.mdx
docs/docs/recipes/integrate-logto/go-web.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/android.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/fragments/_fetch-user-information.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/go-web.mdx

- Add a fetch user information guide for the Android doc.
- Extract the user information section into a doc fragment and shared with the Go doc.
- Upgrade the SDK version to `v1.0.0-alpha.1`
Test locally.

docs: fetch userinfo for android integration guide

---

docs/docs/tutorials/using-cli/README.mdx
docs/docs/tutorials/using-cli/database-alteration.mdx
docs/docs/tutorials/using-cli/install-logto.mdx
docs/docs/tutorials/using-cli/manage-connectors.mdx
docs/docs/tutorials/using-cli/migrate-from-env.mdx

Init CLI tutorial and mark as WIP.

docs(en): init CLI tutorial

---

docs/docs/tutorials/using-cli/README.mdx
docs/docs/tutorials/using-cli/install-logto.mdx

improved content for installing
locally

docs(en): refactor install Logto via CLI

---

docs/docs/recipes/deployment/README.md
docs/docs/tutorials/using-cli/README.mdx
docs/docs/tutorials/using-cli/database-alteration.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/deployment/README.md

add docs and fix typos of database alteration command
locally

docs(en): database alteration command

---

docs/docs/tutorials/using-cli/install-logto.mdx
docs/docs/tutorials/using-cli/migrate-from-env.mdx

docs about migrating existing ENV configs to database
/

docs(en): migrate from env

---

docs/docs/tutorials/get-started/enable-passcode-sign-in.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/enable-passcode-sign-in.mdx

fix typo
fix typo of the URL connector-sendgrid-email
Manually tested.

fix: sendgrid connector repo links in get-started turorial

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

fix an error of Gitpod demo link.

fix: gitpod repo links

---

src/scss/custom.scss

fix side menu icon bug
Chrome somehow is buggy on rendering masks with a background color. 
Before:
After:
test locally
@logto-io/eng

fix(doc): fix side menu icon bug

---

docs/docs/recipes/deployment/README.md
docs/docs/references/core/configuration.md
docs/docs/tutorials/get-started/README.mdx
docs/docs/tutorials/using-cli/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/core/configuration.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

for both en and zh-CN:
- remove `[WIP]` for CLI tutorial
- update get started page
- update configuration
to fit the latest commit.
/

docs: update get started and config

---

docs/docs/tutorials/using-cli/README.mdx
docs/docs/tutorials/using-cli/install-logto.mdx
docs/docs/tutorials/using-cli/manage-connectors.mdx
docs/docs/tutorials/using-cli/migrate-from-env.mdx

- update npx usage since it doesn't need to prepend `--`
- update silent init to use `npx` since there's an issue of passing options directly via `@logto/create` LOG-4432

refactor(en): update npx usage

---

docs/docs/recipes/deployment/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/deployment/README.md

Add missing semicolon in nginx config sample
N/A

fix: add missing semicolon in nginx config sample

---

docs/docs/recipes/deployment/README.md
docs/docs/recipes/interact-with-management-api/README.md
docs/docs/recipes/localization/README.mdx
docs/docs/references/core/README.mdx
docs/docs/tutorials/get-started/create-and-integrate-the-first-app.mdx

add a dedicated page to improve experience
/

docs(en): interact with Management API

---

src/scss/custom.scss

refactor: fix caret color

---

docs/docs/recipes/integrate-logto/fragments/_fetch-user-information.mdx
docs/docs/recipes/integrate-logto/ios.mdx
docs/sdk/Swift/Logto/Protocols/UserInfoProtocol.md
docs/sdk/Swift/Logto/README.md
docs/sdk/Swift/Logto/Structs/IdTokenClaims.md
docs/sdk/Swift/Logto/Structs/LogtoCore.CodeTokenResponse.md
docs/sdk/Swift/Logto/Structs/LogtoCore.OidcConfigResponse.md
docs/sdk/Swift/Logto/Structs/LogtoCore.RefreshTokenTokenResponse.md
docs/sdk/Swift/Logto/Structs/LogtoCore.UserInfoResponse.md

- update iOS SDK userinfo related references
- add fetch user info section in iOS integration guide
local looks good

docs(en): update iOS SDK userinfo related references

---

docs/docs/recipes/integrate-logto/machine-to-machine.mdx
docs/docs/references/core/README.mdx

add note of content-type header for OIDC requests
/

docs(en): add content-type note for OIDC requests

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

Add missing db name to the postgres URLs, as it is required due to a recent update
N/A

fix: add db name to the postgres urls

---

docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

docs: fix header name

---

docs/docs/tutorials/get-started/README.mdx
docs/docs/tutorials/using-cli/install-logto.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

docs: use latest tag for `npm init`

---

docs/docs/references/connectors/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/connectors/README.mdx

Add "learn more" content to connector's target
Local preview

docs: connector target

---

docs/docs/recipes/interact-with-management-api/README.md

Add docs on how to use pagination for management API
Local preview

docs: pagination

---

i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/connectors/README.mdx

Update CHN connector target description.
Check the local CHN docs site.

chore: update CHN connector target description

---

docs/docs/recipes/interact-with-management-api/advanced-user-search.md

mostly migrated from https://github.com/logto-io/logto/pull/2639
local tested, looks good

docs(en-US): advanced user search

---

docs/docs/recipes/web-hooks/README.md
docusaurus.config.js
package.json
pnpm-lock.yaml

web hook recipe
locally look ok

docs(en-US): web hooks

---

docs/docs/recipes/integrate-logto/express.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/express.mdx

Add introduction on how to get access token in Express.
Local preview

docs: get access token

---

docs/docs/tutorials/get-started/enable-passcode-sign-in.mdx
docs/docs/tutorials/get-started/enable-social-sign-in.mdx

we have too many connectors to show, so use plain text and guide user to the repo
locally

docs(en-US): update connector section in get started

---

docs/docs/recipes/rbac/README.md

Add a "not ready" notice on RBAC
N/A

docs: rbac release notice

---

docs/docs/recipes/user-profile/README.md

Draft documentation for building user profile page using Logto's management API.

docs(en): build user profile page with management APIs

---

docs/docs/recipes/deployment/README.md
docs/docs/recipes/protect-your-api/python.mdx
docs/docs/references/core/configuration.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/deployment/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/protect-your-api/python.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/core/configuration.md

replace all rsa references
N/A

fix(doc): replace all rsa references

---

docs/docs/tutorials/get-started/README.mdx
docs/docs/tutorials/using-cli/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

chore: update node version to 18

---

docs/docs/recipes/rbac/README.mdx
docs/docs/recipes/user-profile/README.md

chore: remove unreleased notes

---

docs/docs/recipes/interact-with-management-api/README.md

docs(en): add scope info in Management API guide

---

docs/docs/recipes/integrate-logto/machine-to-machine.mdx

docs(en): add scope in M2M recipe

---

docs/docs/recipes/rbac/protect-resource.mdx

refer to the NIST RBAC model
/

docs(en): update scope-permission tip

---

blog/2022-11-28-ciam-101-authn-identity-sso/index.mdx

blog: capitalize the first letter of tenant

---

blog/2022-11-28-ciam-101-authn-identity-sso/index.mdx

blog: refine definition of authn

---

docs/docs/recipes/integrate-logto/fragments/_fetch-user-information.mdx
docs/docs/recipes/web-hooks/README.md
docs/docs/references/core/README.mdx
docs/docs/references/sdk-convention/fragments/_core_types.md
docs/docs/references/users/README.md
docs/sdk/JavaScript/browser/classes/default.md
docs/sdk/JavaScript/client/classes/default.md
docs/sdk/JavaScript/js/functions/decodeIdToken.md
docs/sdk/JavaScript/node/classes/default.md
docs/sdk/Kotlin/kotlin/io.logto.sdk.core.constant/-claim-name/index.md
docs/sdk/Kotlin/kotlin/io.logto.sdk.core.type/-id-token-claims/index.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/fragments/_fetch-user-information.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/core/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/references/users/README.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Kotlin/kotlin/io.logto.sdk.core.constant/-claim-name/index.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Kotlin/kotlin/io.logto.sdk.core.type/-id-token-claims/index.md

1. refactor: remove deprecated `roleNames`
2. update the `Core Service` management API authentication content from 
to
Test locally.

refactor: remove deprecated `roleNames`

---

blog/2022-11-15-design-for-seamless-sie-1/index.mdx

blog: fix typo

---

docs/docs/recipes/user-profile/README.md

Polish user profile recipe, adding flow chart and tips

refactor: polish user profile recipe

---

blog/2023-02-05-ciam-102-authz-and-rbac/index.md

blog: polish ciam 102

---

docs/docs/recipes/integrate-logto/express.mdx
docs/docs/recipes/integrate-logto/fragments/_fetch-user-information.mdx
docs/docs/recipes/integrate-logto/fragments/_user-information-claims.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/express.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/fragments/_fetch-user-information.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/fragments/_user-information-claims.mdx

add profile scope mapping for express

docs: add profile scope mapping for express

---

docs/docs/recipes/integrate-logto/next-js.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/next-js.mdx

add profile scope mapping for nextjs

docs: add profile scope mapping for nextjs

---

blog/2023-02-16-do-you-need-to-build-auth/index.md
package.json

new blog post to answer the common question
local viewed

blog: do you need to build your own auth for apps

---

blog/2023-02-16-do-you-need-to-build-auth/index.md

- to show a better preview on the blog index
- fix typo for display
locally

blog: add truncate mark

---

docs/docs/recipes/interact-with-management-api/advanced-user-search.md

since it's removed from the api
/

docs(en): remove hide admin parameter

---

blog/2023-02-16-do-you-need-to-build-auth/index.md

blog: update tl;dr section

---

docs/docs/recipes/integrate-logto/next-js.mdx
docs/docs/recipes/integrate-logto/react.mdx
docs/docs/recipes/integrate-logto/vanilla-js.mdx
docs/docs/recipes/integrate-logto/vue.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/ios.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/next-js.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/react.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/vanilla-js.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/recipes/integrate-logto/vue.mdx

Update docs for fetching user information through `userinfo endpoint`

chore: update docs for fetching data from user info endpoint

---

docs/docs/recipes/configure-connectors/README.md
docs/docs/recipes/configure-connectors/connector-setup-tips.md
docs/docs/recipes/create-your-connector/connector-implementation-guide.mdx
docs/docs/references/connectors/README.mdx

1. Add connector DB read/write examples
2. Add details on connector `target` docs, and provide suggestions for different scenarios
3. Reword connector docs.
Check locally.

docs: connector db access, examples of `target` and rewording

---

static/robots.txt

chore: add robots.txt

---

docusaurus.config.js

for verifying domain
local shows the tag

chore: add google verification

---

blog/releases/2023-feb-extended.md
blog/releases/2023-feb.md
blog/releases/2023-jan.md

add release notes in 2023
locally ewviewed

blog: add release notes

---

docs/docs/recipes/interact-with-management-api/advanced-user-search.md

explain default behavior and add tips
/

docs(en): refine search docs

---

blog/releases/2023-feb-extended.md
docs/docs/tutorials/get-started/README.mdx
i18n/zh-cn/docusaurus-plugin-content-docs/current/docs/tutorials/get-started/README.mdx

add CORS policy in quick troubleshooting
locally

docs(en): add CORS policy

---

static/robots.txt

otherwise it cannot crawl sdk data
will crawl again after merge

chore: allow Algolia Crawler for all paths

---

blog/releases/2023-feb-extended.md

add resource indicator change
/

blog: fix 2023-02 release notes

---

package.json
tutorial/build-with-logto/.gitignore
tutorial/build-with-logto/_connector-github.mdx
tutorial/build-with-logto/_connector-google.mdx
tutorial/build-with-logto/_template.mdx
tutorial/build-with-logto/generate.js

generate tutorials from script in cartesian product
generated two tutorials and looks good

feat: use generate script for tutorials

---

docs/docs/recipes/integrate-logto/fragments/_sign-in-note.mdx
docs/docs/recipes/integrate-logto/fragments/_web-sign-in-flow-summary.mdx
tutorial/build-with-logto/_integrate-sdk-react.mdx
tutorial/build-with-logto/_template.mdx

fix several typos in tutorial
local reviewed

docs: fix tutorial typo

---

docs/docs/recipes/configure-storage-providers/README.md

A recipe to show how to setup azure storage.
OR

docs: configure storage provider

---

docs/sdk/Swift/Logto/Protocols/UserInfoProtocol.md
docs/sdk/Swift/Logto/Structs/IdTokenClaims.md
docs/sdk/Swift/Logto/Structs/LogtoCore.UserInfoResponse.md

docs: fix swift user response type

---

docusaurus.config.js
terms/common.scss
terms/of-use/logto-cloud-preview.mdx
terms/privacy-policy.mdx

add Terms of Use for Logto Cloud (Preview) and general Privacy Policy
locally tested

docs: terms and privacy policy

---

terms/privacy-policy.mdx

docs: polish privacy policy

---

terms/common.scss

hide top nav for terms pages
test locally
OR

style(docs): hide top nav for terms pages

---

blog/2023-03-20-announcing-logto-cloud-preview/index.md

blog: cloud preview announcement

---

docs/docs/references/applications/README.mdx
docs/docs/references/resources/README.md

polish the applications  and resources reference
OR

chore(docs): polish the applications reference

---

terms/custom.scss
terms/of-use/cloud.mdx
terms/privacy-policy.mdx

hide terms pages' top nav
test locally
OR

style(docs): hide terms pages top nav

---

blog/2023-03-20-announcing-logto-cloud-preview/index.md

docs: update announcement

---

docs/docs/recipes/manage-users/advanced-user-search.md
docs/docs/tutorials/get-started/README.mdx

docs: update get started

---

terms/privacy-policy.mdx

docs: update privacy policy

---

docs/docs/tutorials/get-started/README.mdx

docs: update docker tag

---

docs/docs/recipes/configure-connectors/configure-social-connector.md
docs/docs/recipes/create-your-connector/connector-implementation-guide.mdx
docs/docs/recipes/customize-sie/custom-css.md
docs/docs/tutorials/get-started/README.mdx

Remove connector DB storage access desc and fix syntax.
Locally reviewed contents.
OR

docs: remove connector db storage access desc and fix syntax

---

blog/releases/2023-mar.md

blog: add 2023 March update

---

docs/docs/references/sdk-convention/_category_.json
docs/docs/references/users/_category_.json
docs/docs/tutorials/get-started/_category_.json
src/scss/custom.scss

fix docs side-bar style
test locally
OR

style(docs): fix docs side bar style

---

docusaurus.config.js

feat(docs): remove i18n lng switch

---

.github/PULL_REQUEST_TEMPLATE.md

override the shared file to simplify template. we can have only summary section for docs PRs

chore: create PULL_REQUEST_TEMPLATE.md

---

docs/docs/recipes/rbac/README.mdx

docs: update rbac letter cases

---

docs/docs/tutorials/using-cli/manage-connectors.mdx

briefing `logto connector link`

docs: add `connector link` command

---

docs/docs/recipes/integrate-logto/flutter/README.mdx
docs/docs/recipes/integrate-logto/flutter/_add_sdk.mdx
docs/docs/recipes/integrate-logto/flutter/_dependency.mdx
docs/docs/recipes/integrate-logto/flutter/_implement_sign_in.mdx
docs/docs/recipes/integrate-logto/flutter/_implement_sign_out.mdx
docs/docs/recipes/integrate-logto/flutter/_init_client.mdx
tutorial/build-with-logto/_integrate-sdk-flutter.mdx
tutorial/build-with-logto/generate.js

Add implement connectors with flutter tutorial docs

chore(docs): add implement connectors with flutter

---

docs/docs/recipes/integrate-logto/next-js.mdx
docs/docs/recipes/integrate-logto/next-js/_add_sdk.mdx
docs/docs/recipes/integrate-logto/next-js/_implement_sign_in.mdx
docs/docs/recipes/integrate-logto/next-js/_init_client.mdx
pnpm-lock.yaml
tutorial/build-with-logto/_integrate-sdk-next.mdx
tutorial/build-with-logto/generate.js

Add instructions on how to integrate GitHub social sign-in into your Next.js application using Logto.

docs: integrate GitHub sign-in with next.js

---

docs/docs/tutorials/using-cli/manage-connectors.mdx

link https://github.com/logto-io/logto/pull/3685

docs: add cli path auto detect

---

blog/releases/2023-mar.md
docs/docs/recipes/configure-storage-providers/README.md

docs: polish storage provider

---

docs/docs/recipes/enable-central-cache/README.md

docs about how to configure Redis

docs: enable central cache

---

docs/docs/recipes/customize-sie/localized-language.md
docs/docs/tutorials/get-started/explore-management-api.md

docs: fix the notification format

---

docs/docs/recipes/user-profile/README.md

Update `user profile` documentation, adding more instructions about detecting and verifying user password, etc.

docs: update user profile documentation

---

docs/docs/recipes/configure-storage-providers/README.md
versioned_docs/version-1.x/docs/recipes/configure-storage-providers/README.md

fix s3 secret name, in Logto's core code, it should be "accessSecretKey"

docs: fix s3 secret name

---

docs/docs/tutorials/using-cli/database-alteration.mdx
versioned_docs/version-1.x/docs/tutorials/using-cli/database-alteration.mdx

provide docs about `logto db alteration rollback` command

docs: update database rollback command

---

tutorial/build-with-logto/_connector-facebook.mdx
tutorial/build-with-logto/generate.js

docs: add facebook connector template

docs: add facebook connector template

---

tutorial/build-with-logto/_connector-twilio.mdx
tutorial/build-with-logto/generate.js

docs: add twilio setup guide

---

docs/docs/recipes/configure-connectors/configure-email-connector.md
docs/docs/recipes/configure-connectors/configure-social-connector.md
docs/docs/recipes/configure-connectors/custom-social-connector-with-standard-protocols.md
docs/docs/tutorials/using-cli/manage-connectors.mdx
versioned_docs/version-1.x/docs/recipes/configure-connectors/configure-email-connector.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/configure-social-connector.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/custom-social-connector-with-standard-protocols.md
versioned_docs/version-1.x/docs/tutorials/using-cli/manage-connectors.mdx

Update connector readme links since old repo have been archived and should use new links from logto-io/logto repo.

docs: update connector readme links

---

tutorial/build-with-logto/_connector-oidc.mdx
tutorial/build-with-logto/generate.js

docs: add oidc guide

---

tutorial/build-with-logto/_connector-saml.mdx
tutorial/build-with-logto/generate.js

docs: add SAML connector guide

---

tutorial/build-with-logto/_connector-oauth2.mdx
tutorial/build-with-logto/generate.js

docs: add oauth2 connector guide

---

docs/docs/tutorials/get-started/README.mdx

link https://github.com/logto-io/logto/pull/3778

docs: support specifying URL during `npm init @logto`

---

tutorial/build-with-logto/_connector-aws-ses.mdx

docs: add aws ses connector guide

---

docs/docs/recipes/integrate-logto/next-js.mdx

add nextjs edge runtime integration guide

docs: add nextjs edge runtime guide

---

docs/docs/recipes/integrate-logto/next-js.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/next-js.mdx
versioned_docs/version-1.x/docs/recipes/user-profile/README.md
versioned_docs/version-1.x/docs/tutorials/get-started/README.mdx

chore: update v1.x docs

---

src/theme/BlogPostItem/Header/Title/index.tsx

fix: do not redirect for non-blog posts

---

tutorial/build-with-logto/_connector-sendgrid.mdx
tutorial/build-with-logto/generate.js

add sendgrid email connector guide

docs: add sendgrid email connector guide

---

docs/docs/recipes/integrate-logto/fragments/_further-readings.md
versioned_docs/version-1.x/docs/recipes/integrate-logto/fragments/_further-readings.md

add rbac link to integration guide

docs: add rbac link to integration guide

---

docs/docs/recipes/deployment/README.md
versioned_docs/version-1.x/docs/recipes/deployment/README.md

Update nginx config sample in `Deployment - Reverse Proxy` section

docs: update nginx config sample

---

src/theme/BlogPostItem/Header/Title/index.tsx

- show an admonition on the top instead of auto redirecting
- remove unnecessary link tags and set canonical url properly

refactor: use a tender approach for redirecting to the new blog

---

about/cloud-preview.mdx

make it more positive and user friendly

docs: update about cloud preview

---

about/cloud-preview.mdx

chore: update TL;DR for about cloud

---

docs/docs/recipes/integrate-logto/machine-to-machine.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/machine-to-machine.mdx

replace localhost url with more friendly content.

docs: refine m2m docs

---

docs/docs/recipes/interact-with-management-api/README.md

remove the misleading programatic sign-in sesion under the management api page.

fix: remove the misleading content

---

docs/docs/recipes/rbac/README.mdx
docs/docs/references/resources/README.md
docs/docs/references/resources/fragments/_api_resource_schema.mdx

docs: default api

---

docs/docs/recipes/integrate-logto/flutter/_dependency.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/flutter/_dependency.mdx

fix the wrong link in the flutter integration guide.

fix(docs): fix  the wrong link

---

docs/docs/references/applications/README.mdx
versioned_docs/version-1.x/docs/references/applications/README.mdx

doc update for https://github.com/logto-io/logto/pull/4028

docs: update application reference

---

docs/docs/recipes/protect-your-api/python.mdx
versioned_docs/version-1.x/docs/recipes/protect-your-api/python.mdx

fix python protect-your-api sample code typo

fix: fix python protect-your-api sample code typo

---

terms/of-use/cloud-preview.mdx
terms/of-use/cloud.mdx
terms/privacy-policy.mdx

update terms of use and privacy policy for cloud

chore: update terms

---

docs/docs/recipes/deployment/README.md
versioned_docs/version-1.x/docs/recipes/deployment/README.md

fixes the database alteration yaml indent and imagePullPolicy value

fix: database alteration yaml

---

docs/sdk/JavaScript/remix/README.md
docs/sdk/JavaScript/remix/functions/function.makeLogtoRemix.md
docs/sdk/JavaScript/remix/type-aliases/type-alias.LogtoContext.md
versioned_docs/version-1.x/sdk/JavaScript/remix/README.md
versioned_docs/version-1.x/sdk/JavaScript/remix/functions/function.makeLogtoRemix.md
versioned_docs/version-1.x/sdk/JavaScript/remix/type-aliases/type-alias.LogtoContext.md

Add SDK references for @logto/remix

docs: add SDK references for @logto/remix

---

docs/sdk/JavaScript/express/README.md
docs/sdk/JavaScript/express/enumerations/enumeration.ReservedScope.md
docs/sdk/JavaScript/express/enumerations/enumeration.UserScope.md
docs/sdk/JavaScript/express/functions/function.handleAuthRoutes.md
docs/sdk/JavaScript/express/functions/function.withLogto.md
docs/sdk/JavaScript/express/type-aliases/type-alias.InteractionMode.md
docs/sdk/JavaScript/express/type-aliases/type-alias.LogtoContext.md
docs/sdk/JavaScript/express/type-aliases/type-alias.LogtoExpressConfig.md
docs/sdk/JavaScript/express/type-aliases/type-alias.Middleware.md
versioned_docs/version-1.x/sdk/JavaScript/express/README.md
versioned_docs/version-1.x/sdk/JavaScript/express/enumerations/enumeration.ReservedScope.md
versioned_docs/version-1.x/sdk/JavaScript/express/enumerations/enumeration.UserScope.md
versioned_docs/version-1.x/sdk/JavaScript/express/functions/function.handleAuthRoutes.md
versioned_docs/version-1.x/sdk/JavaScript/express/functions/function.withLogto.md
versioned_docs/version-1.x/sdk/JavaScript/express/type-aliases/type-alias.InteractionMode.md
versioned_docs/version-1.x/sdk/JavaScript/express/type-aliases/type-alias.LogtoContext.md
versioned_docs/version-1.x/sdk/JavaScript/express/type-aliases/type-alias.LogtoExpressConfig.md
versioned_docs/version-1.x/sdk/JavaScript/express/type-aliases/type-alias.Middleware.md

Add SDK references for @logto/express

docs: add SDK references for @logto/express

---

docs/docs/tutorials/using-cli/migrate-from-env.mdx
docs/docs/tutorials/using-cli/translation.mdx

add docs for `translate sync-keys` and `translate sync`

docs: cli translation commands

---

docs/docs/tutorials/using-cli/translation.mdx
versioned_docs/version-1.x/docs/tutorials/using-cli/translation.mdx

refactor: fix typo

---

docs/docs/references/applications/README.mdx
versioned_docs/version-1.x/docs/references/applications/README.mdx

fixing refresh token related description to match the real behavior

fix: refresh token switch description

---

docs/docs/recipes/configure-connectors/email-connector/configure-popular-email-service.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/email-connector/configure-popular-email-service.md

Improve connectors by adding how to add custom HTML code to connector config template

docs: show how to add custom HTML to connector config template

---

docs/docs/recipes/integrate-logto/vanilla-js/_handle_redirect.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/vanilla-js/_handle_redirect.mdx

The existing code example omits passing in the href to the `handleSignInCallback` function. Fix that.

docs: update handleSignInCallback in vanilla-js docs

---

versioned_docs/version-1.x/docs/recipes/integrate-logto/flutter/_dependency.mdx

Update the dart SDK android config.
Should set the action android:exported="true" so it is globally visible.

fix: update the dart SDK android config

---

docs/docs/recipes/configure-storage-providers/README.md

Add s3 region and endpoint description for this [change](https://github.com/logto-io/logto/pull/4439)

feat: add s3 region and endpoint description

---

docs/docs/tutorials/get-started/README.mdx
versioned_docs/version-1.x/docs/tutorials/get-started/README.mdx

chore: remove preview

---

docs/docs/recipes/integrate-logto/flutter/_dependency.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/flutter/_dependency.mdx

fix: update flutter docs

---

versioned_docs/version-1.x/docs/recipes/rbac/protect-resource.mdx

Fix wrong typing 'cusom_data' to 'custom_data'

fix: typo 'cusom_data' to 'custom_data'

---

docs/docs/recipes/interact-with-management-api/README.md
docusaurus.config.js
versioned_docs/version-1.x/docs/recipes/interact-with-management-api/README.md

chore: update api reference links

---

docs/docs/fragments/_cloud_only_notification.mdx
docs/docs/recipes/custom-domain/README.mdx
docs/docs/recipes/environment-tags/README.mdx

feat: add env tag doc

---

docs/docs/recipes/webhooks/securing-your-webhooks.md

refactor(docs): add using raw body note when verifying logto signature

refactor(docs): add using raw body note when verifying logto signature

---

docs/docs/recipes/protect-your-api/spring-boot.mdx
versioned_docs/version-1.x/docs/recipes/protect-your-api/spring-boot.mdx

Set the jws algorithm to ES384.

fix(docs): update the spring boot doc

---

blog/2023-03-20-announcing-logto-cloud-preview/index.md
blog/releases/2023-feb.md
docs/docs/recipes/configure-connectors/social-connector/README.md
docs/docs/recipes/configure-connectors/social-connector/custom-social-connector-with-standard-protocols.md
docs/docs/recipes/rbac/README.mdx
docs/docs/references/resources/README.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/email-connector/README.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/sms-connector/README.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/social-connector/README.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/social-connector/configure-popular-social-connector.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/social-connector/custom-social-connector-with-standard-protocols.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/social-connector/enable-social-sign-in.md
versioned_docs/version-1.x/docs/recipes/rbac/README.mdx
versioned_docs/version-1.x/docs/references/resources/README.md

use sentence case to match our convention

chore: use sentence case

---

docs/docs/recipes/integrate-logto/next-js-13/_implement_sign_in.mdx
docs/docs/recipes/integrate-logto/next-js.mdx
docs/docs/recipes/integrate-logto/next-js/_implement_sign_in.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/next-js-13/_implement_sign_in.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/next-js.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/next-js/_implement_sign_in.mdx

This PR fix several issues in Next.js guide:
1. Remove unused "next/router" import.
2. Remove duplicated and incorrect fetch user information part.
3. Fix wrong export in code snippet.

fix: several issues in nextjs guide

---

docs/docs/recipes/configure-connectors/email-connector/configure-popular-email-service.md
versioned_docs/version-1.x/docs/recipes/configure-connectors/email-connector/configure-popular-email-service.md

docs: typo fix for configure-popular-email-service.md

---

docs/docs/recipes/integrate-logto/next-js.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/next-js.mdx

`handleAuthRoutes()` should be used to handle many urls matched by `[action].js`, while `handleUser()` should be used to handle exact url matched by `user.js`.

docs: fix fetch user info issue for next.js

---

docs/docs/recipes/integrate-logto/next-js.mdx
versioned_docs/version-1.x/docs/recipes/integrate-logto/next-js.mdx

This fix make the code more next.js native by utilizing next.js builtin object to redirect unauthenticated users to sign in page.
Ref: https://nextjs.org/docs/pages/api-reference/functions/get-server-side-props#redirect

docs: revise next.js doc for sign in redirection

---

docs/docs/README.mdx

Updated the introduction of doc

refactor: update readme

---

docs/docs/recipes/tenant-type/README.mdx

refactor: update tenant type doc

---

docs/docs/recipes/integrate-logto/README.md
docs/sdk/fragments/_implement-sign-out-route-notice.md
docs/sdk/python/README.mdx
docs/sdk/python/_implement_callback_route.md
docs/sdk/python/_implement_sign_in_route.mdx
docs/sdk/python/_implement_sign_out_route.mdx
docs/sdk/python/_init_logto_client.mdx
docs/sdk/python/_installation.md
docs/sdk/python/_python_tutorial_tip.md
docs/sdk/python/_test_your_application.md
docs/sdk/python/api-resources/_config_api_resources.mdx
docs/sdk/python/api-resources/_fetch_access_token_for_api_resources.mdx
docs/sdk/python/api-resources/_fetch_organization_token_for_user.mdx
docs/sdk/python/api-resources/code/_config_organization_code.md
docs/sdk/python/api-resources/code/_config_resources_code.md
docs/sdk/python/api-resources/code/_config_resources_with_scopes_code.md
docs/sdk/python/api-resources/code/_config_resources_with_shared_scopes_code.md
docs/sdk/python/api-resources/code/_get_access_token_code.md
docs/sdk/python/api-resources/code/_get_organization_access_token_code.md
docs/sdk/python/scopes-and-claims/_scopes_and_claims.mdx
docs/sdk/python/scopes-and-claims/_scopes_and_claims_code.md

Add Python SDK tutorial, and update [the SDK](https://github.com/logto-io/python/pull/20) as well.

chore: add python SDK tutorial

---

docs/sdk/python/_implement_sign_in_route.mdx

add homepage implementation to Python SDK tutorial.

docs: add homepage implementation to Python SDK tutorial

---

docs/sdk/fragments/_config_api_resources.mdx
docs/sdk/fragments/_scopes_and_claims.mdx
docs/sdk/native/swift/README.mdx
docs/sdk/web/dotnet-blazor-wasm/README.mdx
docs/sdk/web/dotnet-mvc/README.mdx
docs/sdk/web/dotnet-mvc/_add_middleware.md
docs/sdk/web/dotnet-mvc/_add_sign_in.md
docs/sdk/web/dotnet-mvc/_add_sign_out.md
docs/sdk/web/dotnet-mvc/_fetch-tokens.md
docs/sdk/web/dotnet-mvc/_implement_buttons.md
docs/sdk/web/dotnet-mvc/_installation.md
docs/sdk/web/dotnet-mvc/_scopes_and_claims.mdx
docs/sdk/web/dotnet-mvc/_scopes_and_claims_code.md
docs/sdk/web/dotnet-mvc/_special_id_token_claims.md
docs/sdk/web/dotnet-mvc/_test_your_application.md
docs/sdk/web/dotnet-mvc/_the_user_object.md
docs/sdk/web/dotnet-mvc/_tutorial_tip.md
docs/sdk/web/dotnet-mvc/api-resources/_configure-api-resources.mdx
docs/sdk/web/dotnet-mvc/api-resources/code/_config_resources_code.md
docs/sdk/web/dotnet-mvc/api-resources/code/_config_resources_with_scopes_code.md

- resolve LOG-7901
- refactor some common fragments

docs: add .NET Core MVC guide

---

docs/sdk/web/dotnet-mvc/_implement_buttons.md
docs/sdk/web/dotnet-razor/README.mdx
docs/sdk/web/dotnet-razor/_implement_buttons.md

docs: add .NET Core Razor Pages guide

---

tutorial/build-with-logto/fragments/_intro.mdx

improve readability and fix formatting in tutorial files
- Disable `prettier` formatting for easier readability in `_intro.mdx`
- Fix the formatting of component links in `_intro.mdx`
- Remove a redundant declaration in the prerequisites section of `_intro.mdx`

fix: improve readability and fix formatting in tutorial files

---

docs/docs/recipes/integrate-logto/README.md
docs/sdk/js/next-app-router/README.mdx
docs/sdk/js/next-app-router/_handle_authentication_status.mdx
docs/sdk/js/next-app-router/_implement_sign_in.mdx
docs/sdk/js/next-app-router/_implement_sign_out.mdx
docs/sdk/js/next-app-router/_init_client.mdx
docs/sdk/js/next-app-router/_tutorial_tip.mdx
docs/sdk/js/next-app-router/api-resources/_config_api_resources.mdx
docs/sdk/js/next-app-router/api-resources/_fetch_access_token_for_api_resources.mdx
docs/sdk/js/next-app-router/api-resources/_fetch_organization_token_for_user.mdx
docs/sdk/js/next-app-router/api-resources/code/_config_organization_code.md
docs/sdk/js/next-app-router/api-resources/code/_config_resources_code.md
docs/sdk/js/next-app-router/api-resources/code/_config_resources_with_scopes_code.md
docs/sdk/js/next-app-router/api-resources/code/_config_resources_with_shared_scopes_code.md
docs/sdk/js/next-app-router/api-resources/code/_get_access_token_code.md
docs/sdk/js/next-app-router/api-resources/code/_get_organization_access_token_code.md

Update Next.js App Router integration guide, remove the old "next 13" guide.

refactor: update nextjs app router integration guide

---

docs/sdk/web/dotnet-blazor-wasm/README.mdx
docs/sdk/web/dotnet-blazor-wasm/_api_resources.mdx
docs/sdk/web/dotnet-blazor-wasm/_fetch_user_information.mdx
docs/sdk/web/dotnet-blazor-wasm/_installation.md
docs/sdk/web/dotnet-blazor-wasm/_integration.md
docs/sdk/web/dotnet-blazor-wasm/_test_your_application.md
docs/sdk/web/dotnet-blazor-wasm/_tutorial_tip.md
docs/sdk/web/dotnet-blazor-wasm/_update_razor_pages.md

reorg the guide to align with our convention and make it suitable for reuse

refactor: reorg blazor wasm guide

---

docs/sdk/web/dotnet-mvc/README.mdx
docs/sdk/web/dotnet-mvc/_add_authentication.md
docs/sdk/web/dotnet-mvc/_add_sign_in_redirect_uri.md
docs/sdk/web/dotnet-mvc/_add_sign_out_redirect_uri.md
docs/sdk/web/dotnet-mvc/_implement_buttons.md
docs/sdk/web/dotnet-razor/README.mdx
tutorial/build-with-logto/_integrate-sdk-dotnet-core-mvc.mdx
tutorial/build-with-logto/_integrate-sdk-dotnet-core-razor-pages.mdx

fix typos, update content, make them better

refactor: polish guides

---

docs/sdk/web/dotnet-blazor-server/README.mdx
docs/sdk/web/dotnet-blazor-server/_add-routes.md
docs/sdk/web/dotnet-blazor-server/_authorize-view-component.md
docs/sdk/web/dotnet-blazor-server/_fetch-token-in-razor-components.md
docs/sdk/web/dotnet-blazor-server/_implement-buttons.md
docs/sdk/web/dotnet-mvc/README.mdx

docs: add .NET Core Blazor Server guide

---

docs/docs/recipes/configure-connectors/email-connector/configure-popular-email-service.md

Just add link to mailgun connector in popular email connectors doc.

docs: add link to mailgun connector in email connector doc

---

tutorial/authors.yml
tutorial/build-with-logto/fragments/_intro.mdx

refactor: update logto descriptions

refactor: update logto descriptions

---

tutorial/build-with-logto/_integrate-sdk-dotnet-core-blazor-server.mdx
tutorial/build-with-logto/_integrate-sdk-dotnet-core-blazor-webassembly.mdx

refactor: fix imports

---

docs/docs/recipes/protected-app/README.mdx

Add docs for the new Protected App.

docs: add protected app doc

---

docs/sdk/native/flutter/_integration.mdx
docs/sdk/native/flutter/_scopes-and-claims.mdx
docs/sdk/native/flutter/code-snippets/_get-organization-access-token.md

fix(docs): fix flutter code

---

docs/sdk/spa/react/_guide-tip.mdx
docs/sdk/spa/vue/_guide-tip.mdx

Add YouTube links to React and Vue SDK integration guides

chore: add youtube links to vue and react guides

---

docs/sdk/machine-to-machine/general/README.mdx
docs/sdk/native/android/_guide-tip.md
docs/sdk/web/next-app-router/_guide-tip.mdx

feat: add SDK integration video link

feat: add SDK integration video link

---

docs/docs/recipes/manage-users/you-dont-need-a-user-table.md

fix: fix typo

---

docs/docs/recipes/custom-domain/use-custom-domain.md

Add CAA records guide to custom domain's troubleshooting section.

fix: add caa records guide

---

docs/sdk/fragments/_config-api-resources.mdx
docs/sdk/fragments/_scopes-and-claims.mdx
docs/sdk/spa/angular/README.mdx
docs/sdk/spa/angular/_api-resources.mdx
docs/sdk/spa/angular/_get-user-information.mdx
docs/sdk/spa/angular/_guide-tip.md
docs/sdk/spa/angular/_installation.mdx
docs/sdk/spa/angular/_integration.mdx
docs/sdk/spa/angular/code/_config-resources-code.md
docs/sdk/spa/angular/code/_config-resources-with-scopes-code.md
docs/sdk/spa/react/README.mdx
docs/sdk/spa/vanilla-js/README.mdx
docs/sdk/spa/vue/README.mdx
static/img/logo/angular.svg

add angular sdk guide. generated tutorial will be added later.

docs: add angular guide

---

docs/sdk/fragments/_further-readings.md

refactor: update further readings for sdk docs

refactor: update further readings for sdk docs

---

docs/sdk/web/php/README.mdx
docs/sdk/web/php/_handle-authentication-status.md
docs/sdk/web/php/_implement-sign-in-route.mdx
docs/sdk/web/python/README.mdx
docs/sdk/web/python/_handle-authentication-status.md
docs/sdk/web/python/_implement-sign-in-route.mdx
tutorial/build-with-logto/_integrate-sdk-php.mdx
tutorial/build-with-logto/_integrate-sdk-python.mdx

Reorg content in Python and PHP tutorials to align with Android SDK.

docs: reorg content in Python and PHP tutorials to align with Android SDK

---

docs/sdk/native/android/README.mdx
docs/sdk/native/flutter/README.mdx
docs/sdk/spa/angular/README.mdx
docs/sdk/spa/dotnet-blazor-wasm/README.mdx
docs/sdk/spa/react/README.mdx
docs/sdk/spa/vue/README.mdx
docs/sdk/web/dotnet-blazor-server/README.mdx
docs/sdk/web/dotnet-mvc/README.mdx
docs/sdk/web/dotnet-razor/README.mdx
docs/sdk/web/express/README.mdx
docs/sdk/web/go/README.mdx
docs/sdk/web/next-app-router/README.mdx
docs/sdk/web/next/README.mdx
docs/sdk/web/php/_prerequisites.md
docs/sdk/web/python/README.mdx

fix: update get-started doc link for sdk docs

fix: update get-started doc link for sdk docs

---

docs/sdk/native/android/README.mdx
docs/sdk/native/android/_check-integration.md
docs/sdk/native/flutter/_integration.mdx
docs/sdk/spa/angular/_integration.mdx
docs/sdk/spa/react/README.mdx
docs/sdk/spa/react/_check-integration.mdx
docs/sdk/spa/vue/README.mdx
docs/sdk/spa/vue/_check-integration.mdx
docs/sdk/web/dotnet-blazor-server/README.mdx
docs/sdk/web/dotnet-mvc/README.mdx
docs/sdk/web/dotnet-mvc/_test-your-application.md
docs/sdk/web/dotnet-razor/README.mdx
docs/sdk/web/next-app-router/README.mdx
docs/sdk/web/next/README.mdx
docs/sdk/web/next/_check-integration.mdx
docs/sdk/web/nuxt/_integration.mdx
docs/sdk/web/php/README.mdx
docs/sdk/web/php/_test-your-application.md
docs/sdk/web/python/README.mdx
docs/sdk/web/python/_test-your-application.md

reuse component for better maintainability

refactor: reuse checkpoint component

---

docs/sdk/spa/vanilla-js/README.mdx
docs/sdk/spa/vanilla-js/_check-integration.mdx
docs/sdk/spa/vanilla-js/_guide-tip.mdx
docs/sdk/spa/vanilla-js/_handle-authentication-status.mdx
docs/sdk/spa/vanilla-js/_handle-redirect.mdx
docs/sdk/spa/vanilla-js/_implement-sign-in.mdx
docs/sdk/spa/vanilla-js/_implement-sign-out.mdx
docs/sdk/spa/vanilla-js/_init-client.mdx
docs/sdk/spa/vanilla-js/code/_config-organization-code.md
docs/sdk/spa/vanilla-js/code/_config-resources-code.md
docs/sdk/spa/vanilla-js/code/_config-resources-with-scopes-code.md
docs/sdk/spa/vanilla-js/code/_config-resources-with-shared-scopes-code.md
docs/sdk/spa/vanilla-js/code/_get-access-token-code.md
docs/sdk/spa/vanilla-js/code/_get-organization-access-token-code.md
docs/sdk/spa/vanilla-js/code/_scopes-and-claims-code.md
tutorial/build-with-logto/_integrate-sdk-vanilla-js.mdx

Update new vanilla js SDK guide

feat(docs): update new vanilla js SDK guide

---

tutorial/build-with-logto/_integrate-sdk-react.mdx
tutorial/build-with-logto/_integrate-sdk-vue.mdx
tutorial/build-with-logto/generate.js
tutorial/build-with-logto/generated-vue-apple.mdx
tutorial/build-with-logto/generated-vue-aws-ses.mdx
tutorial/build-with-logto/generated-vue-azure-ad.mdx
tutorial/build-with-logto/generated-vue-discord.mdx
tutorial/build-with-logto/generated-vue-facebook.mdx
tutorial/build-with-logto/generated-vue-github.mdx
tutorial/build-with-logto/generated-vue-google.mdx
tutorial/build-with-logto/generated-vue-kakao.mdx
tutorial/build-with-logto/generated-vue-naver.mdx
tutorial/build-with-logto/generated-vue-oauth2.mdx
tutorial/build-with-logto/generated-vue-oidc.mdx
tutorial/build-with-logto/generated-vue-saml.mdx
tutorial/build-with-logto/generated-vue-sendgrid.mdx
tutorial/build-with-logto/generated-vue-twilio.mdx

fix the react SDK tutorial fragment and add new vue tutorial

fix(docs): fix react SDK tutorial fragment

---

docs/docs/recipes/protected-app/README.mdx

docs: refactor protected app figure

---

docs/sdk/fragments/_apply-authorization-token.md
docs/sdk/fragments/_get-authorization-token.md
docs/sdk/native/swift/README.mdx
docs/sdk/native/swift/api-resources/_config-api-resources.mdx
docs/sdk/native/swift/api-resources/_fetch-access-token-for-api-resources.mdx
docs/sdk/native/swift/api-resources/_index.mdx
docs/sdk/native/swift/api-resources/code/_config-resources-code.md
docs/sdk/native/swift/api-resources/code/_config-resources-with-scopes-code.md
docs/sdk/native/swift/api-resources/code/_config-resources-with-shared-scopes-code.md
docs/sdk/native/swift/api-resources/code/_get-access-token-code.md

follow the new template, resolves LOG-8027 and LOG-7949

refactor: update swift sdk guide

---

docs/docs/recipes/user-profile/README.md
tutorial/build-with-logto/generated-vue-apple.mdx
tutorial/build-with-logto/generated-vue-aws-ses.mdx
tutorial/build-with-logto/generated-vue-azure-ad.mdx
tutorial/build-with-logto/generated-vue-discord.mdx
tutorial/build-with-logto/generated-vue-facebook.mdx
tutorial/build-with-logto/generated-vue-github.mdx
tutorial/build-with-logto/generated-vue-google.mdx
tutorial/build-with-logto/generated-vue-kakao.mdx
tutorial/build-with-logto/generated-vue-naver.mdx
tutorial/build-with-logto/generated-vue-oauth2.mdx
tutorial/build-with-logto/generated-vue-oidc.mdx
tutorial/build-with-logto/generated-vue-saml.mdx
tutorial/build-with-logto/generated-vue-sendgrid.mdx
tutorial/build-with-logto/generated-vue-twilio.mdx

- Update a confusing diagram in user profile page
- Also fix some typos in the generated contents

chore: update diagram and fix typo

---

docs/docs/recipes/organizations/configuration.mdx

update docs w/ small typos and fix the `invite:users` part.

fix(docs): :pencil2: remove some typos

---

docs/docs/recipes/interact-with-management-api/README.md
docs/docs/recipes/migrations/README.mdx

docs: migration

---

docs/sdk/web/next-app-router/README.mdx
docs/sdk/web/next-app-router/_handle-authentication-status.mdx
docs/sdk/web/next-app-router/_implement-sign-in.mdx
docs/sdk/web/next-app-router/_implement-sign-out.mdx
docs/sdk/web/next-app-router/_prepare-configs.mdx
docs/sdk/web/next-app-router/api-resources/code/_config-organization-code.md
docs/sdk/web/next-app-router/api-resources/code/_config-resources-code.md
docs/sdk/web/next-app-router/api-resources/code/_config-resources-with-scopes-code.md
docs/sdk/web/next-app-router/api-resources/code/_config-resources-with-shared-scopes-code.md
docs/sdk/web/next-app-router/api-resources/code/_get-access-token-code.md
docs/sdk/web/next-app-router/api-resources/code/_get-organization-access-token-code.md

use built-in helpers for next app router

feat: use built-in helpers for next app router

---

docs/sdk/machine-to-machine/general/README.mdx

Add custom domain notice to management api.

docs: add custom domain notice to management api

---

tutorial/build-with-logto/_integrate-sdk-expo-react-native.mdx
tutorial/build-with-logto/generate.js
tutorial/build-with-logto/generated-expo-react-native-apple.mdx
tutorial/build-with-logto/generated-expo-react-native-aws-ses.mdx
tutorial/build-with-logto/generated-expo-react-native-azure-ad.mdx
tutorial/build-with-logto/generated-expo-react-native-discord.mdx
tutorial/build-with-logto/generated-expo-react-native-facebook.mdx
tutorial/build-with-logto/generated-expo-react-native-github.mdx
tutorial/build-with-logto/generated-expo-react-native-google.mdx
tutorial/build-with-logto/generated-expo-react-native-kakao.mdx
tutorial/build-with-logto/generated-expo-react-native-naver.mdx
tutorial/build-with-logto/generated-expo-react-native-oauth2.mdx
tutorial/build-with-logto/generated-expo-react-native-oidc.mdx
tutorial/build-with-logto/generated-expo-react-native-saml.mdx
tutorial/build-with-logto/generated-expo-react-native-sendgrid.mdx
tutorial/build-with-logto/generated-expo-react-native-twilio.mdx

add generated content for expo

chore: add expo content

---

docs/docs/tutorials/get-started/introduction.mdx

Add docs for Cloud collaboration feature.

docs: cloud collaboration

---

docs/docs/recipes/openid-connect/authentication-parameters/README.md

per https://github.com/logto-io/docs/pull/634/files#r1560387366

refactor: polish content

---

docs/docs/recipes/protect-your-api/spring-boot.mdx

Update the protect API spring boot instruction. Update the code sample to user the latest SpringSecurity version.

refactor(docs): update the protect api spring boot instruction

---

terms/custom.scss
terms/of-service.mdx
terms/of-use/cloud.mdx
terms/privacy-policy-2307.mdx

chore: update tos and privacy policy

---

src/components/Topbar/index.module.scss
src/components/Topbar/index.tsx
terms/custom.scss
terms/of-service.mdx
terms/of-use/cloud-preview.mdx
terms/of-use/cloud.mdx
terms/privacy-policy-2307.mdx
terms/privacy-policy.mdx

remove footer, add a simple header

refactor: polish terms pages style

---

docusaurus.config.js

refactor: update plausible domain

---

docusaurus.config.js

update script to track conversion funnel

chore: update plausible script

---

docusaurus.config.js

Fix the legacy url redirection. The previous PR (#658) got it wrong and it didn't work

fix: legacy link redirection

---

docs/docs/recipes/custom-jwt/README.md

custom JWT feature now available at OSS v1.16.0.

chore: custom JWT feature now available at OSS v1.16.0

---

tutorial/build-with-logto/_connector-hugging-face.mdx
tutorial/build-with-logto/generate.js
tutorial/build-with-logto/generated-android-hugging-face.mdx
tutorial/build-with-logto/generated-dotnet-core-blazor-server-hugging-face.mdx
tutorial/build-with-logto/generated-dotnet-core-blazor-webassembly-hugging-face.mdx
tutorial/build-with-logto/generated-dotnet-core-mvc-hugging-face.mdx
tutorial/build-with-logto/generated-dotnet-core-razor-pages-hugging-face.mdx
tutorial/build-with-logto/generated-expo-react-native-hugging-face.mdx
tutorial/build-with-logto/generated-express-hugging-face.mdx
tutorial/build-with-logto/generated-flutter-hugging-face.mdx
tutorial/build-with-logto/generated-go-hugging-face.mdx
tutorial/build-with-logto/generated-ios-swift-hugging-face.mdx
tutorial/build-with-logto/generated-next-hugging-face.mdx
tutorial/build-with-logto/generated-php-hugging-face.mdx
tutorial/build-with-logto/generated-python-hugging-face.mdx
tutorial/build-with-logto/generated-react-hugging-face.mdx
tutorial/build-with-logto/generated-vanilla-js-hugging-face.mdx
tutorial/build-with-logto/generated-vue-hugging-face.mdx

docs: add hugging face integration tutorial

docs: add hugging face integration tutorial

---

docs/docs/recipes/custom-domain/configure-custom-domain-in-console.md

Add troubleshooting guide on "held zone" issue.

feat: add held zone issue troubleshooting

---

docs/quick-starts/framework/webflow/README.mdx
docs/quick-starts/framework/webflow/_checkpoint-test-your-webflow-site.md
docs/quick-starts/framework/webflow/_get-user-information.mdx
docs/quick-starts/framework/webflow/_guide-tip.mdx
docs/quick-starts/framework/webflow/_handle-authentication-status.mdx
docs/quick-starts/framework/webflow/_handle-redirect.mdx
docs/quick-starts/framework/webflow/_implement-sign-in.mdx
docs/quick-starts/framework/webflow/_implement-sign-out.mdx
docs/quick-starts/framework/webflow/_init-client.mdx
docs/quick-starts/framework/webflow/_scopes-and-claims-code.mdx
docs/quick-starts/framework/webflow/api-resources/_config-api-resources.mdx
docs/quick-starts/framework/webflow/api-resources/_fetch-access-token-for-api-resources.mdx
docs/quick-starts/framework/webflow/api-resources/_fetch-organization-token-for-user.mdx
docs/quick-starts/framework/webflow/api-resources/_index.mdx
docs/quick-starts/framework/webflow/api-resources/code/_config-organization-code.md
docs/quick-starts/framework/webflow/api-resources/code/_config-resources-code.md
docs/quick-starts/framework/webflow/api-resources/code/_config-resources-with-scopes-code.md
docs/quick-starts/framework/webflow/api-resources/code/_config-resources-with-shared-scopes-code.md
docs/quick-starts/framework/webflow/api-resources/code/_get-access-token-code.md
docs/quick-starts/framework/webflow/api-resources/code/_get-organization-access-token-code.md
static/img/logo/webflow.svg

Add full integration guide for Webflow in "Quick starts".

docs: add webflow full integration guide

---

docs/docs/recipes/organizations/README.mdx

chore: update availability for organizations

chore: update availability for organizations

---

docs/docs/recipes/custom-domain/README.mdx

Remove "iframe" in custom domains, because we don't support it.

fix: remove iframe description

---

docs/quick-starts/framework/wordpress/README.mdx

Add WordPress integration tutorial.

feat: add wordpress integration

---

src/components/Gallery/index.module.scss
src/scss/custom.scss

Fix the hover style of the gallery items, use box shadow instead of background color change

fix: use box shadow as the gallery item hover state

---

docs/quick-starts/framework/wordpress/README.mdx

fix: wordpress integration guide logo and description

---

docs/docs/recipes/customize-sie/custom-css.md
docs/docs/references/connectors/README.mdx
docs/quick-starts/fragments/_scope-claim-list.md
package.json
pnpm-lock.yaml

add sso_identities claims to the userinfo doc

feat(docs): add sso_identities claims to the userinfo doc

---

docs/docs/recipes/customize-sie/custom-css.md
docs/docs/recipes/webhooks/webhook-events.md
docs/docs/references/connectors/README.mdx
docs/quick-starts/fragments/_scope-claim-list.md
package.json
pnpm-lock.yaml

Add databook events API map to the webhook docs

feat(docs): add datahook events API map

---

docs/quick-starts/framework/nuxt/scopes-and-claims/_scopes-and-claims-code.md

Fix the UserScope contant usage.

fix: fix nuxt guide userscope

---

docs/docs/recipes/interact-with-management-api/README.md

`management API` -> `Management API`

fix: uppercase management api

---

docs/quick-starts/fragments/_config-api-resources.mdx
docs/quick-starts/fragments/_web-configure-redirect-uris.mdx
docs/quick-starts/framework/ruby/README.mdx
docs/quick-starts/framework/ruby/_get-user-information.mdx
docs/quick-starts/framework/ruby/_guide-tip.md
docs/quick-starts/framework/ruby/_installation.md
docs/quick-starts/framework/ruby/_integration.mdx
docs/quick-starts/framework/ruby/api-resources/_config-api-resources.mdx
docs/quick-starts/framework/ruby/api-resources/_fetch-access-token-for-api-resources.mdx
docs/quick-starts/framework/ruby/api-resources/_fetch-organization-token-for-user.mdx
docs/quick-starts/framework/ruby/api-resources/_index.mdx
docs/quick-starts/framework/ruby/api-resources/code/_config-organization-code.md
docs/quick-starts/framework/ruby/api-resources/code/_config-resources-code.md
docs/quick-starts/framework/ruby/api-resources/code/_config-resources-with-scopes-code.md
docs/quick-starts/framework/ruby/api-resources/code/_config-resources-with-shared-scopes-code.md
docs/quick-starts/framework/ruby/api-resources/code/_get-access-token-code.md
docs/quick-starts/framework/ruby/api-resources/code/_get-organization-access-token-code.md
docs/quick-starts/framework/ruby/scopes-and-claims/_scopes-and-claims-code.md
docs/quick-starts/framework/ruby/scopes-and-claims/_scopes-and-claims.mdx
docusaurus.config.js
src/scss/custom.scss

docs: add ruby docs

---

docs/docs/references/openid-connect/backchannel-logout/README.md

add brief docs about backchannel logout

docs: add backchannel logout docs

---

docs/docs/references/users/README.md
docs/quick-starts/fragments/_scope-claim-list.md

update scope - claim mappings according to our latest update.

docs: update user claims

---

docs/docs/recipes/rbac/protect-resource.mdx

Add manage user permission change.

feat: add manage user permission change

---

docs/integrations/email/aliyun-dm/README.mdx
docs/integrations/email/aws-ses/README.mdx
docs/integrations/email/mailgun/README.mdx
docs/integrations/email/sendgrid-email/README.mdx
docs/integrations/email/smtp/README.mdx
docs/integrations/sms/aliyun-sms/README.mdx
docs/integrations/sms/smsaero/README.mdx
docs/integrations/sms/tencent-sms/README.mdx
docs/integrations/sms/twilio-sms/README.mdx
docs/integrations/social/alipay-native/README.mdx
docs/integrations/social/alipay-web/README.mdx
docs/integrations/social/apple/README.mdx
docs/integrations/social/github/README.mdx
docs/integrations/social/wechat-native/README.mdx
docs/integrations/social/wechat-web/README.mdx

Update invalid reference links in connector guides

chore: update invalid links

---

docs/quick-starts/framework/expo/README.mdx

Add troubleshooting in section in the Expo guide

docs: add troubleshooting in expo guide

---

docs/docs/tutorials/get-started/README.mdx

docs: add hardware recommendation for self-hosted instance

---

docs/quick-starts/framework/swift/README.mdx

Update the SDK `Get user information`  section to align with other SDKs. Demonstrate how to retrieve user information from both ID token claims and the userinfo endpoint.

fix(docs): refine swift SDK getUserInfo content

---

docs/quick-starts/framework/flutter/_get-user-info.mdx

Update the Flutter Get user information section to align with other SDKs. Demonstrate how to retrieve user information from both ID token claims and the userinfo endpoint.

fix(docs): update the flutter get user information section

---

docs/quick-starts/fragments/_get-user-info-apis.mdx

refactor: get user info apis component

---

docs/docs/tutorials/get-started/sign-in-experience.mdx

explain the current sign-in experience for end users

docs: sign-in experience explained

---

docs/quick-starts/fragments/_claims-need-network-request.mdx
docs/quick-starts/fragments/_scopes-claims-introduction.md
docs/quick-starts/framework/nuxt/_get-user-information.mdx
docs/quick-starts/framework/nuxt/_integration.mdx
docs/quick-starts/framework/ruby/_get-user-information.mdx
docs/quick-starts/framework/ruby/_integration.mdx
docs/quick-starts/framework/swift/README.mdx

- add `_claims-need-network-request.mdx` for reuse
- update doc structure according to the latest convention

refactor: update ruby, nuxt, and swift

---

docs/docs/recipes/rbac/protect-resource.mdx
docs/quick-starts/fragments/_get-user-info-apis.mdx
docs/quick-starts/framework/dotnet-blazor-wasm/README.mdx
docs/quick-starts/framework/express/_handle-authentication-status.mdx
docs/quick-starts/framework/nuxt/_get-user-information.mdx
docs/quick-starts/framework/swift/README.mdx

docs: align get user information section title

docs: align get user information section title

---

docs/quick-starts/framework/flutter/README.mdx
docs/quick-starts/framework/flutter/_api-resources.mdx
docs/quick-starts/framework/flutter/_dependency.mdx
docs/quick-starts/framework/flutter/_get-user-info.mdx
docs/quick-starts/framework/flutter/_installation.mdx
docs/quick-starts/framework/flutter/_integration.mdx
docs/quick-starts/framework/flutter/_organization.mdx
docs/quick-starts/framework/flutter/_tip.md
docs/quick-starts/framework/flutter/code-snippets/_display-userinfo.md
docs/quick-starts/framework/flutter/code-snippets/_fetch-userinfo.md
docs/quick-starts/framework/flutter/code-snippets/_get-resource-access-token.md
docs/quick-starts/framework/flutter/code-snippets/_organization-config-code.md
docs/quick-starts/framework/flutter/code-snippets/_resource-config-code.md
docs/quick-starts/framework/flutter/code-snippets/_resource-with-scopes-config-code.md
docs/quick-starts/framework/flutter/code-snippets/_resource-with-shared-scopes-config-code.md
docs/quick-starts/framework/flutter/code-snippets/_scopes-code.mdx

refactor(docs): polish flutter SDK tutorial

---

docs/quick-starts/framework/expo/README.mdx
docs/quick-starts/framework/expo/_integration.mdx
docs/quick-starts/framework/expo/api-resources/code/_config-organization-code.md
docs/quick-starts/framework/expo/api-resources/code/_config-resources-code.md
docs/quick-starts/framework/expo/api-resources/code/_config-resources-with-scopes-code.md
docs/quick-starts/framework/expo/api-resources/code/_config-resources-with-shared-scopes-code.md
docs/quick-starts/framework/expo/api-resources/code/_get-access-token-code.md
docs/quick-starts/framework/expo/api-resources/code/_get-organization-access-token-code.md
docs/quick-starts/framework/expo/get-user-information/_fetch-user-info-code.mdx
docs/quick-starts/framework/expo/get-user-information/_index.mdx
docs/quick-starts/framework/expo/get-user-information/_scopes-and-claims-code.mdx

refactor(docs): polish expo SDK content

---

docs/quick-starts/framework/capacitor-js/README.mdx
docs/quick-starts/framework/capacitor-js/_fetch-userinfo-code.md
docs/quick-starts/framework/capacitor-js/_get-user-information.mdx
docs/quick-starts/framework/capacitor-js/_integration.mdx

reorg the section title aligns with other SDKs. The content is up to date.

chore: reorg capacitor sections

---

docs/docs/recipes/configure-connectors/email-connector/enable-email-sign-in.md
docs/docs/recipes/configure-connectors/sms-connector/enable-SMS-sign-in.md
docs/docs/recipes/configure-connectors/social-connector/enable-social-sign-in.md
docs/docs/recipes/customize-sie/README.md
docs/docs/recipes/inspect-audit-logs/README.mdx
docs/docs/recipes/interact-with-management-api/README.md
docs/docs/recipes/logto-as-idp/README.mdx
docs/docs/recipes/logto-as-idp/configure-3rd-party-app-in-console.mdx
docs/docs/recipes/manage-users/admin-console.md
docs/docs/recipes/organizations/configuration.mdx
docs/docs/recipes/organizations/understand-how-it-works.mdx
docs/docs/recipes/rbac/manage-permissions-and-roles.md
docs/docs/recipes/webhooks/configure-webhooks-in-console.md
docs/docs/tutorials/get-started/README.mdx
docs/docs/tutorials/get-started/introduction.mdx
docs/quick-starts/fragments/_configure-post-sign-out-redirect-uri.mdx
docs/quick-starts/fragments/_configure-redirect-uri.mdx
docs/quick-starts/framework/wordpress/README.mdx
tutorial/build-with-logto/fragments/_add-social-connector.mdx
tutorial/build-with-logto/fragments/_create-application.mdx
tutorial/build-with-logto/fragments/_enable-passwordless-connector.mdx
tutorial/build-with-logto/fragments/_enable-social-connector.mdx
tutorial/build-with-logto/fragments/_save-your-configuration.mdx

update Logto-related content to use sentence case

chore: use sentence case for Logto Console content

---

docs/quick-starts/framework/go/README.mdx
docs/quick-starts/framework/go/_create-session-storage.md
docs/quick-starts/framework/go/_get-user-information.mdx
docs/quick-starts/framework/go/_guide-tip.md
docs/quick-starts/framework/go/_implement-callback-route.md
docs/quick-starts/framework/go/_implement-sign-in-route.mdx
docs/quick-starts/framework/go/_implement-sign-out-route.mdx
docs/quick-starts/framework/go/_init-logto-client.mdx
docs/quick-starts/framework/go/_installation.md
docs/quick-starts/framework/go/_test-your-application.md
docs/quick-starts/framework/go/api-resources/_fetch-organization-token-for-user.mdx
docs/quick-starts/framework/go/api-resources/code/_config-organization-code.md
docs/quick-starts/framework/go/api-resources/code/_config-resources-code.md
docs/quick-starts/framework/go/api-resources/code/_config-resources-with-scopes-code.md
docs/quick-starts/framework/go/api-resources/code/_config-resources-with-shared-scopes-code.md
docs/quick-starts/framework/go/api-resources/code/_get-organization-access-token-code.md
docs/quick-starts/framework/go/scopes-and-claims/_scopes-and-claims-code.md
src/scss/custom.scss

docs: update go quick guide

---

docs/quick-starts/framework/android/README.mdx
docs/quick-starts/framework/android/_implement-sign-in-and-sign-out.mdx
docs/quick-starts/framework/android/_init-logto-client.md
docs/quick-starts/framework/android/_installation.mdx
docs/quick-starts/framework/android/api-resources/_fetch-organization-token-for-user.mdx
docs/quick-starts/framework/android/api-resources/code/_config-organization-code.md
docs/quick-starts/framework/android/api-resources/code/_config-resources-code.md
docs/quick-starts/framework/android/api-resources/code/_config-resources-with-scopes-code.md
docs/quick-starts/framework/android/api-resources/code/_config-resources-with-shared-scopes-code.md
docs/quick-starts/framework/android/api-resources/code/_get-access-token-code.md
docs/quick-starts/framework/android/api-resources/code/_get-organization-access-token-code.md

docs: update android quick start guide

docs: update android quick start guide

---

docs/docs/recipes/organizations/configuration.mdx
docs/docs/recipes/organizations/integration.mdx
docs/docs/recipes/organizations/organization-invitations.mdx
docs/docs/recipes/organizations/understand-how-it-works.mdx
docs/docs/recipes/rbac/manage-permissions-and-roles.md
docs/docs/recipes/webhooks/webhook-request.md

add machine-to-machine sections in organization docs.

docs: m2m apps in organizations

---

docs/docs/recipes/organizations/configuration.mdx

a brief explanation about organization mfa requirement

docs: organization mfa requirement

---

.github/workflows/commitlint.yml
.github/workflows/deploy.yml
.github/workflows/main.yml

upgrade workflow to use the latest pnpm by default

ci: upgrade pnpm workflow

---

docs/quick-starts/framework/chrome-extension/_integration.mdx

add the explanation of redirect-based sign-in. the user info part reuses the one in vanilla js, so no update needed.
resolves LOG-9401

docs: improve chrome extension quick start

---

docs/quick-starts/framework/java-spring-boot/README.mdx
docs/quick-starts/framework/java-spring-boot/_scopes-and-claims.mdx

Polish the spring boot guide. Since we do not have an official SDK provided, the spring-boot integration guide has a different structure. Especially it does have the API resource and fetch user info section. 
1. For getting userinfo, it is automatically handled by the OAuthClient which will always fetch the userinfo endpoint to get the user details. 
2. It is complicated to fetch an API access token using a refresh token after a user is authenticated. We have it implemented in the sample code. However, it requires lots of custom codes and class methods overwrites. We'll leave the implementation to the developers for now. Instead of adding them to the official integration guide.

docs: polish the spring boot guide

---

docs/docs/recipes/logto-as-idp/README.mdx
docs/docs/recipes/single-sign-on/README.md

fix(docs): remove coming soom tags

---

docs/quick-starts/fragments/_claims-need-network-request.mdx
docs/quick-starts/framework/angular/README.mdx
docs/quick-starts/framework/angular/_get-user-information.mdx
docs/quick-starts/framework/angular/_guide-tip.md
docs/quick-starts/framework/angular/_installation.mdx
docs/quick-starts/framework/angular/_integration.mdx
docs/quick-starts/framework/angular/code/_config-resources-code.md
docs/quick-starts/framework/angular/code/_config-resources-with-scopes-code.md

Update angular integration guide

refactor: angular integration guide

---

docs/docs/concepts/authn-vs-authz.mdx
docs/docs/concepts/sign-in-experience.mdx

provide an overview of the Logto auth models

docs: explain authentication and authorization

---

docusaurus.config.js

we are not using this event but it counts for our billing. remove it first

chore: remove any page view event

---

docs/docs/recipes/impersonation/README.mdx

Add docs for user impersonation.

feat: add impersonation

---

docs/quick-starts/generic/machine-to-machine/README.mdx
docusaurus.config.js

refactor: add http syntax highlighting

---

docusaurus.config.js

see https://github.com/logto-io/website/pull/552

chore: update plausible urls

---

docs/docs/concepts/authn-vs-authz.mdx

update links to released features

docs: update branding links

---

docs/docs/references/using-cli/rotate-signing-keys.mdx

feat: add zero trust guide

---

docs/quick-starts/framework/passport/README.mdx
docs/quick-starts/framework/passport/_guide-tip.mdx
docs/quick-starts/framework/passport/_installation.mdx
docs/quick-starts/framework/passport/_integration.mdx
docs/quick-starts/framework/passport/_scopes-and-claims-code.md
docs/quick-starts/framework/passport/_scopes-and-claims.mdx
static/img/logo/passport.svg

Add passport.js guide. The original content is in this blog: https://blog.logto.io/integrate-with-passportjs/

feat: add passport guide

---

docs/quick-starts/framework/next-app-router/_get-user-information.mdx

feat: add next js route handlers guide

---

docs/quick-starts/framework/next-app-router/README.mdx

add getAccessTokenRSC and getOrganizationTokenRSC

feat: add getAccessTokenRSC

---

docs/docs/recipes/custom-jwt/README.md

When PAT is ready, token exchange does not equal to impersonation anymore, and custom JWT context is only available in impersonation, so update the doc to prevent misunderstanding.

fix: add impersonation description

---

static/robots.txt

chore: remove disallow in robots.txt

---

docs/docs/recipes/customize-sie/bring-your-ui.md
docs/docs/recipes/customize-sie/check-out-the-live-preview.md
docs/docs/recipes/customize-sie/custom-css.md

Draft documentation for "Bring your UI" feature

docs: bring your ui

---

docs/docs/recipes/customize-sie/bring-your-ui.md
docs/docs/references/tunnel-cli/README.mdx

Update tunnel CLI documentation since it's now a standalone service, separated from `@logto/cli`

refactor: tunnel cli docs

---

docs/docs/recipes/manage-users/personal-access-token.mdx
docs/docs/recipes/manage-users/you-dont-need-a-user-table.md

feat: add personal access token docs

---

docs/docs/recipes/customize-sie/bring-your-ui.md

Polish content.
- sign-in experience -> Sign-in Experience
- experience API -> Experience API

refactor(docs): polish content for bring your ui

---

docs/docs/references/tunnel-cli/README.mdx
docs/docs/references/tunnel-cli/deploy.mdx

Add documentation for the new `deploy` command in Logto Tunnel CLI.

feat(docs): deploy custom ui using cli

---

docs/docs/recipes/customize-sie/localized-language.md
docs/docs/references/translate-cli/README.mdx
docs/docs/references/using-cli/translation.mdx

Change `phrases-ui` to `phrases-experiences`.

fix(docs): change phrases-ui to phrases-experiences

---

docs/docs/get-started/welcome.mdx

fix the tenant member limit for dev tenants, should be 20

fix: fix the tenant member limit for dev tenants

---

docs/quick-starts/framework/next-auth/_config-provider.mdx

fixing several issues of the documentation, including a typo ~~router~~ route.

fix: fix typos and usage errors of next auth

---

docusaurus.config.js

refactor: add gtag and clarity

---

docusaurus.config.js

need to use a different id for another domain

refactor: update clarity id

---

docs/docs/references/applications/README.mdx

Improve docs for "Rotate refresh token" feature.

refactor: improve docs for rotate refresh token

---

docusaurus.config.ts

Enable breadcrumb feature in docs pages

feat: enable breadcrumb

---

docs/docs/recipes/customize-sie/bring-your-ui.md

Add experience sample project link.

docs: add experience sample repo link

---

docs/docs/references/tenants/README.md

to reflect our status quo, resolve LOG-10084

chore: update regions

---

docusaurus.config.ts

Redirect the incorrect PAT link from Console.

fix: redirect pat link

---

docs/docs/recipes/manage-users/admin-console.md

Update docs/recipes/manage-users/admin-console.md, fixed a typo (changed Mange to Manage on line 83)

fix: fixed a typo in docs

---

src/scss/custom.scss

Add gradient background to the top of the main doc area.

style: add gradient background color to main doc area

---

docs/connectors/email-connectors/README.mdx
docs/connectors/sms-connectors/README.mdx
docs/connectors/social.mdx
docs/integrations/email/http-mail/README.mdx
docs/integrations/email/postmark/README.mdx
docs/integrations/sms/gatewayapi-sms/README.mdx
docs/integrations/sms/smsaero/README.mdx
docs/integrations/sms/vonage-sms/README.mdx

1. update docs v2 connector guide links
2. add missing connector integration guides for: vonage, gateway api, postmark, http mail

chore: add missing connector integration guides and update docs links

---

docs/developer/custom-token-claims/README.mdx
docs/developer/webhooks/README.mdx
docs/introduction/README.mdx
src/components/CloudLink/index.module.scss
src/components/CloudLink/index.tsx
src/scss/custom.scss
src/theme/Footer/index.module.scss

- Update introduction page links
- Improve global styles including sidebar caveats and topbar nav items

refactor: update introduction page links and improve css styles

---

docusaurus.config.ts
src/components/Button/index.module.scss
src/components/Button/index.tsx
src/components/Topbar/index.module.scss
src/theme/BlogLayout/index.tsx
src/theme/Navbar/Content/index.tsx
src/theme/Navbar/Content/styles.module.css
terms/custom.scss

Refreshed topbar with Logto Cloud button.

feat: new topbar with logto cloud button

---

docs/end-user-flows/account-settings/by-management-api.mdx
docs/end-user-flows/consent-screen.mdx
docs/end-user-flows/enterprise-sso/README.mdx
docs/end-user-flows/enterprise-sso/idp-initiated-sso.mdx
docs/end-user-flows/enterprise-sso/sp-initiated-sso.mdx
docs/end-user-flows/mfa/backup-codes.md
docs/end-user-flows/mfa/configure-mfa.mdx
docs/end-user-flows/sign-out.mdx
docs/end-user-flows/sign-up-and-sign-in/README.mdx
docs/end-user-flows/sign-up-and-sign-in/disable-user-registration.mdx
docs/end-user-flows/sign-up-and-sign-in/reset-password.mdx
docs/end-user-flows/sign-up-and-sign-in/sign-in.mdx
docs/end-user-flows/sign-up-and-sign-in/sign-up.mdx
docs/end-user-flows/sign-up-and-sign-in/social-sign-in.mdx

Update internal links under the end-user-flow.

fix: update internal links under end-user-flow

---

docs/integrate-logto/interact-with-management-api/README.md
docs/integrate-logto/third-party-application/README.mdx
docs/integrate-logto/third-party-application/oidc-third-party-application/permission-management.mdx

docs: update integration doc links

---

docs/concepts/core-service/README.mdx
docs/introduction/README.mdx
docs/introduction/plan-your-architecture/_generic-features.mdx
docs/introduction/plan-your-architecture/b2b.mdx
docs/introduction/plan-your-architecture/b2c.mdx
docs/logto-oss/deployment-and-configuration.mdx
docs/logto-oss/get-started-with-oss.mdx

refactor: update internal links

---

docs/authorization/README.mdx
docs/developer/custom-token-claims/create-script.mdx
docs/quick-starts/database/hasura/README.mdx

chore: update wording

---

docs/end-user-flows/sign-up-and-sign-in/README.mdx

fix: add missing links

---

docs/end-user-flows/account-settings/by-account-api.mdx
docs/end-user-flows/account-settings/by-management-api.mdx

Migrate account API docs to docs V2. 
Also refactors the account settings by Management API doc's content.

feat(docs): migrate account API docs

---

docs/introduction/plan-your-architecture/README.mdx
src/scss/custom.scss
src/theme/DocCard/index.tsx
src/theme/DocCard/styles.module.css
src/theme/DocCardList/index.module.scss
src/theme/DocCardList/index.tsx

Adjust content font sizes and spacing (margins and paddings)

refactor: adjust content margin and padding

---

docs/quick-starts/third-party/oidc/README.mdx

Update third party app doc slug

refactor: update third party oidc doc slug

---

src/scss/custom.scss

refactor: add indent to 4th and above level sidebar items

---

static/_redirects

chore: update redirect urls

---

docs/introduction/README.mdx

chore: update content

---

static/_redirects

add the missing target for the catch-all redirect
tested using the preview ⬇️

refactor: fix catch-all redirect

---

docs/connectors/enterprise-connectors.mdx
docs/developers/custom-token-claims/common-use-cases.mdx
docs/developers/webhooks/README.mdx
docs/integrate-logto/integrate-logto-into-your-application/README.mdx
docs/introduction/README.mdx

- Adjust resource URLs alignment
- Some mdx code refactoring

refactor: various minor content updates

---

docs/developers/custom-token-claims/README.mdx
docs/introduction/plan-your-architecture/b2b.mdx
docs/introduction/plan-your-architecture/b2c.mdx
docs/quick-starts/framework/passport/README.mdx
src/scss/custom.scss
src/theme/DocItem/Layout/index.module.scss
src/theme/DocItem/Layout/index.tsx
static/img/logo/passport-dark.svg

- Adjust page layout, also limit main content max-width to 1000px
- Update "passport.js" logos
- Other trivial style updates

fix: various UI issues

---

src/scss/custom.scss
src/theme/DocBreadcrumbs/Items/Home/index.tsx

refactor: update breadcrumbs styles

---

src/components/Gallery/index.tsx
src/components/Topbar/index.tsx
src/hooks/useCurrentLocalePrefix.ts

- fix `<Gallery>` display issue for non-English locales
- use localized url for Logto logo

refactor: improve gallery i18n

---

docs/integrations/sms/tencent-sms/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/integrations/sms/tencent-sms/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/integrations/sms/tencent-sms/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/integrations/sms/tencent-sms/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/integrations/sms/tencent-sms/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/sms/tencent-sms/README.mdx

use zh-CN content to translate to other languages

fix: tecent sms content

---

docs/integrations/email/aliyun-dm/README.mdx
docs/integrations/email/aws-ses/README.mdx
docs/integrations/sms/aliyun-sms/README.mdx
docs/integrations/sms/gatewayapi-sms/README.mdx
docs/integrations/sms/tencent-sms/README.mdx

1. translate Tencent Cloud SMS to English
2. delete the useless tips

refactor: tencent-cloud-sms-translation

---

docusaurus.config.ts

Remove the console log that used to print cf pages env var.

chore: remove console log

---

src/theme/EditMetaRow/index.tsx

Fix plausible manual track with custom props.
https://plausible.io/docs/custom-props/for-custom-events#tag-custom-properties-using-the-manual-method

fix: plausible manual track with custom props

---

src/theme/EditMetaRow/index.tsx

Remove unnecessary plausible properties

chore: remove unnecessary plausible property

---

pnpm-lock.yaml
src/components/Button/index.module.scss
src/scss/_underscore.scss
src/scss/custom.scss
src/theme/Navbar/Content/styles.module.css

refactor: searchbar refresh

---

docusaurus.config.ts
package.json
pnpm-lock.yaml
src/components/Button/index.module.scss
src/components/Gallery/index.module.scss
src/scss/custom.scss
src/theme/DocItem/Layout/index.module.scss
src/theme/DocItem/Layout/index.tsx
src/theme/EditMetaRow/index.tsx
src/theme/Footer/Logo/index.tsx
src/theme/Footer/Logo/styles.module.css
src/theme/Layout/index.tsx

Improve performance and UI layout

refactor: various performance and UI improvements

---

src/scss/custom.scss
src/theme/DocItem/Layout/index.module.scss

- Fix the layout shift issue on mobile when initializing the docs page.
- Use minimized searchbar icon on mobile

fix: layout issues on mobile

---

docs/integrations/email/mailgun/README.mdx
docs/integrations/email/smtp/README.mdx
docs/integrations/sms/aliyun-sms/README.mdx
docs/integrations/sms/tencent-sms/README.mdx
docs/integrations/sms/twilio-sms/README.mdx
docs/integrations/social/alipay-native/README.mdx
docs/integrations/social/alipay-web/README.mdx
docs/integrations/social/apple/README.mdx
docs/integrations/social/azuread/README.mdx
docs/integrations/social/github/README.mdx
docs/integrations/social/google/README.mdx
docs/integrations/social/huggingface/README.mdx
docs/integrations/social/naver/README.mdx
docs/integrations/social/oauth2/README.mdx
docs/integrations/social/oidc/README.mdx
docs/integrations/social/wechat-native/README.mdx
docs/integrations/social/wechat-web/README.mdx
docs/introduction/README.mdx

1. Change the old style of Note/Tip/Caution/URL in Connector Guides to the new components
2. Delete some descriptions on the homepage

refactor: change some details in docs

---

docs/logto-oss/troubleshooting-oss.mdx

Fix invalid heading IDs in the OSS troubleshooting FAQs

fix: oss troubleshooting faqs

---

docs/integrations/fragments/_guide-tip.mdx
docs/integrations/social/feishu-web/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/integrations/social/feishu-web/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/integrations/social/feishu-web/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/integrations/social/feishu-web/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/integrations/social/feishu-web/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/integrations/social/feishu-web/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/feishu-web/README.mdx

Update translation of Feishu connector guide.

refactor: update feishu connector guide

---

src/scss/custom.scss

Update tip bubble border color in dark mode.

style: update tip border color

---

docs/quick-starts/framework/nuxt/README.mdx

fix: add middleware and api routes usage for nuxt

---

static/robots.txt

chore: add i18n sitemaps

---

docs/quick-starts/framework/java-spring-boot/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/java-spring-boot/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/java-spring-boot/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/java-spring-boot/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/java-spring-boot/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/java-spring-boot/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/java-spring-boot/README.mdx
static/_redirects

Update java spring boot slug and add redirect rules

fix: update java springboot guide slug

---

docusaurus.config.ts
i18n/de/code.json
i18n/es/code.json
i18n/fr/code.json
i18n/pt-BR/code.json
plugins/tutorial-generator/utils.ts
src/hooks/use-categorized-tutorial-metadata.ts
src/theme/BlogLayout/index.module.scss
src/theme/BlogLayout/index.tsx
src/theme/BlogListPage/index.module.scss
src/theme/BlogListPage/index.tsx
src/theme/BlogPostItem/Container/index.tsx
src/theme/BlogPostItem/Footer/index.tsx
src/theme/BlogPostItem/Header/Info/index.tsx
src/theme/BlogPostItem/Header/SelectionDropdown/index.module.scss
src/theme/BlogPostItem/Header/SelectionDropdown/index.tsx
src/theme/BlogPostItem/Header/Title/index.tsx
src/theme/BlogPostItem/Header/Title/styles.module.css
src/theme/BlogPostItem/Header/TitleWithHighlights/index.module.scss
src/theme/BlogPostItem/Header/TitleWithHighlights/index.tsx
src/theme/BlogPostItem/Header/TitleWithSelectionDropdown/index.module.scss
src/theme/BlogPostItem/Header/TitleWithSelectionDropdown/index.tsx
src/theme/BlogPostItem/index.module.scss
src/theme/BlogPostItem/index.tsx
src/theme/BlogPostItems/index.module.scss
src/theme/BlogPostItems/index.tsx

refactor: docs tutorial a x b cross selection list page

---

src/theme/BlogPostItem/Header/SelectionDropdown/index.module.scss
src/theme/BlogPostItem/Header/TitleWithSelectionDropdown/index.module.scss

Improve the selection dropdown styles, as well as responsiveness in mobile view.

refactor: improve tutorial selection dropdown styles

---

docusaurus.config.ts
i18n/de/docusaurus-theme-classic/footer.json
i18n/es/docusaurus-theme-classic/footer.json
i18n/fr/docusaurus-theme-classic/footer.json
i18n/ja/docusaurus-theme-classic/footer.json
i18n/pt-BR/docusaurus-theme-classic/footer.json
i18n/zh-CN/docusaurus-theme-classic/footer.json

Add footer item as the entrance to "Build X with Y" tutorials

feat: add entrance to build x with y tutorials

---

docusaurus.config.ts

Add tutorial links in the sitemap

chore: add tutorial links in sitemap

---

docs/quick-starts/framework/dotnet-mvc/_configure-redirect-uris.mdx
i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-mvc/_configure-redirect-uris.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-mvc/_configure-redirect-uris.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-mvc/_configure-redirect-uris.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-mvc/_configure-redirect-uris.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-mvc/_configure-redirect-uris.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/dotnet-mvc/_configure-redirect-uris.mdx

Fix incorrect redirect URLs in the dotnet-mvc related guide templates.

fix: incorrect redirect URLs in dotnet-mvc guide templates

---

docs/authorization/organization-template/configure-organization-template.mdx
docs/authorization/role-based-access-control/protect-api-resources-with-rbac.mdx
i18n/de/docusaurus-plugin-content-docs/current/authorization/organization-template/configure-organization-template.mdx
i18n/de/docusaurus-plugin-content-docs/current/authorization/role-based-access-control/protect-api-resources-with-rbac.mdx
i18n/es/docusaurus-plugin-content-docs/current/authorization/organization-template/configure-organization-template.mdx
i18n/es/docusaurus-plugin-content-docs/current/authorization/role-based-access-control/protect-api-resources-with-rbac.mdx
i18n/fr/docusaurus-plugin-content-docs/current/authorization/organization-template/configure-organization-template.mdx
i18n/fr/docusaurus-plugin-content-docs/current/authorization/role-based-access-control/protect-api-resources-with-rbac.mdx
i18n/ja/docusaurus-plugin-content-docs/current/authorization/organization-template/configure-organization-template.mdx
i18n/ja/docusaurus-plugin-content-docs/current/authorization/role-based-access-control/protect-api-resources-with-rbac.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/authorization/organization-template/configure-organization-template.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/authorization/role-based-access-control/protect-api-resources-with-rbac.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/authorization/organization-template/configure-organization-template.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/authorization/role-based-access-control/protect-api-resources-with-rbac.mdx

fix: incorrect config property name used in code samples

---

docs/quick-starts/framework/android/README.mdx
tutorial/build-with-logto/fragments/_create-application.mdx
tutorial/build-with-logto/generated-android-apple.mdx
tutorial/build-with-logto/generated-android-aws-ses.mdx
tutorial/build-with-logto/generated-android-azure-ad.mdx
tutorial/build-with-logto/generated-android-discord.mdx
tutorial/build-with-logto/generated-android-facebook.mdx
tutorial/build-with-logto/generated-android-github.mdx
tutorial/build-with-logto/generated-android-google-workspace-enterprise-sso.mdx
tutorial/build-with-logto/generated-android-google.mdx
tutorial/build-with-logto/generated-android-hugging-face.mdx
tutorial/build-with-logto/generated-android-kakao.mdx
tutorial/build-with-logto/generated-android-microsoft-entra-id-oidc-enterprise-sso.mdx
tutorial/build-with-logto/generated-android-microsoft-entra-id-saml-enterprise-sso.mdx
tutorial/build-with-logto/generated-android-naver.mdx
tutorial/build-with-logto/generated-android-oauth2.mdx
tutorial/build-with-logto/generated-android-oidc-enterprise-sso.mdx
tutorial/build-with-logto/generated-android-oidc.mdx
tutorial/build-with-logto/generated-android-okta-enterprise-sso.mdx
tutorial/build-with-logto/generated-android-saml-enterprise-sso.mdx
tutorial/build-with-logto/generated-android-saml.mdx
tutorial/build-with-logto/generated-android-sendgrid.mdx
tutorial/build-with-logto/generated-android-twilio.mdx
tutorial/build-with-logto/metadata.json

Update a frontmatter metadata in android SDK guide. This metadata is used in the generated "Build X with Y" tutorials.

refactor: android sdk guide metadata and re-generate tutorials

---

i18n/de/docusaurus-plugin-content-docs/current/quick-starts/framework/android/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/quick-starts/framework/android/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/quick-starts/framework/android/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/quick-starts/framework/android/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/quick-starts/framework/android/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/framework/android/README.mdx

This file will trigger the transaltion

fix: transalte android readme

---

static/_redirects

chore: add more redirect rules

---

docs/integrations/social/x/README.mdx
docs/integrations/social/x/_integration.mdx
i18n/de/docusaurus-plugin-content-docs/current/integrations/social/x/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/integrations/social/x/_integration.mdx
i18n/es/docusaurus-plugin-content-docs/current/integrations/social/x/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/integrations/social/x/_integration.mdx
i18n/fr/docusaurus-plugin-content-docs/current/integrations/social/x/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/integrations/social/x/_integration.mdx
i18n/ja/docusaurus-plugin-content-docs/current/integrations/social/x/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/integrations/social/x/_integration.mdx
i18n/ko/docusaurus-plugin-content-docs/current/integrations/social/x/README.mdx
i18n/ko/docusaurus-plugin-content-docs/current/integrations/social/x/_integration.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/integrations/social/x/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/integrations/social/x/_integration.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/x/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/x/_integration.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/integrations/social/x/README.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/integrations/social/x/_integration.mdx

Add X connector integration guide.

feat: add x social connector

---

static/robots.txt

Add new ko and zh-TW locales to sitemap

chore: add new locales to sitemap

---

docs/integrations/social/line/README.mdx
docs/integrations/social/line/_integration.mdx
i18n/de/docusaurus-plugin-content-docs/current/integrations/social/line/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/integrations/social/line/_integration.mdx
i18n/es/docusaurus-plugin-content-docs/current/integrations/social/line/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/integrations/social/line/_integration.mdx
i18n/fr/docusaurus-plugin-content-docs/current/integrations/social/line/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/integrations/social/line/_integration.mdx
i18n/ja/docusaurus-plugin-content-docs/current/integrations/social/line/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/integrations/social/line/_integration.mdx
i18n/ko/docusaurus-plugin-content-docs/current/integrations/social/line/README.mdx
i18n/ko/docusaurus-plugin-content-docs/current/integrations/social/line/_integration.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/integrations/social/line/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/integrations/social/line/_integration.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/line/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/line/_integration.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/integrations/social/line/README.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/integrations/social/line/_integration.mdx

feat: add line guide

---

i18n/es/docusaurus-plugin-content-docs/current/user-management/manage-users.mdx

Fix a mis-translated "warning" box in Spanish translation

fix: warning box in spanish translation

---

translate.mjs

Update translation script:
- Bulk run for all locales without specifying one locale after another
- Add a new `--silent` option to be able to run without asking for user confirms

refactor: update translate script to support bulk run all locales

---

.github/workflows/content-generation.yml

Automate the following process when a PR is merged into master branch:
- Generate and sync heading IDs to all docs including i18n translations
- Run translation CLI when new changes are made to English version docs
- Generate "Build X with Y" tutorials
- Create a PR and include all changed made in the above steps

feat: add github workflow to automate doc content generation

---

.github/workflows/content-generation.yml

Add OpenAI env vars for the translation CLI in Action workflow

fix: add openai env vars for translation cli

---

docs/connectors/email-connectors/email-templates.mdx
i18n/de/docusaurus-plugin-content-docs/current/connectors/email-connectors/email-templates.mdx
i18n/es/docusaurus-plugin-content-docs/current/connectors/email-connectors/email-templates.mdx
i18n/fr/docusaurus-plugin-content-docs/current/connectors/email-connectors/email-templates.mdx
i18n/ja/docusaurus-plugin-content-docs/current/connectors/email-connectors/email-templates.mdx
i18n/ko/docusaurus-plugin-content-docs/current/connectors/email-connectors/email-templates.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/connectors/email-connectors/email-templates.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/connectors/email-connectors/email-templates.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/connectors/email-connectors/email-templates.mdx

feat: update email templates doc

---

docs/integrations/social/x/README.mdx
plugins/tutorial-generator/utils.ts
write-heading-ids.mjs

Improve the slug generation method used in tutorial plugin and `write-heading-ids.mjs` script

refactor: improve tutorial slug generation method

---

.github/workflows/content-generation.yml

Run `pnpm lint --fix` before committing code in the content auto-generation workflow

refactor: lint before commit

---

i18n/de/docusaurus-plugin-content-docs/current/user-management/user-data.mdx
i18n/es/docusaurus-plugin-content-docs/current/user-management/user-data.mdx
i18n/fr/docusaurus-plugin-content-docs/current/user-management/user-data.mdx
i18n/ja/docusaurus-plugin-content-docs/current/user-management/user-data.mdx
i18n/ko/docusaurus-plugin-content-docs/current/user-management/user-data.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/user-management/user-data.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/user-management/user-data.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/user-management/user-data.mdx

Update i18n translations for `/user-management/user-data.mdx`

refactor: update translations

---

docs/integrations/social/linkedin/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/ko/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/feishu-web/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/integrations/social/linkedin/README.mdx

Fix wrong content in LinkedIn connector guide.

fix: wrong content in LinkedIn connector guide

---

docusaurus.config.ts

chore: update i18n labels

---

plugins/tutorial-generator/index.ts
tutorial/build-with-logto/metadata.json

Fix tutorial generator. Make sure it generates tutorial metadata for en locale

fix: tutorial generator should generate metadata for en locale

---

docs/quick-starts/framework/angular/README.mdx
docs/quick-starts/framework/angular/_for-tutorial.mdx
docs/quick-starts/framework/capacitor-js/README.mdx
docs/quick-starts/framework/capacitor-js/_for-tutorial.mdx
docs/quick-starts/framework/chrome-extension/README.mdx
docs/quick-starts/framework/chrome-extension/_for-tutorial.mdx
docs/quick-starts/framework/java-spring-boot/README.mdx
docs/quick-starts/framework/java-spring-boot/_configure-application.mdx
docs/quick-starts/framework/java-spring-boot/_for-tutorial.mdx
docs/quick-starts/framework/java-spring-boot/_guide-tip.md
docs/quick-starts/framework/java-spring-boot/_implementation.mdx
docs/quick-starts/framework/next-app-router/README.mdx
docs/quick-starts/framework/next-app-router/_for-tutorial.mdx
docs/quick-starts/framework/next-auth/README.mdx
docs/quick-starts/framework/next-auth/_for-tutorial.mdx
docs/quick-starts/framework/nuxt/README.mdx
docs/quick-starts/framework/nuxt/_for-tutorial.mdx
docs/quick-starts/framework/passport/README.mdx
docs/quick-starts/framework/passport/_for-tutorial.mdx
docs/quick-starts/framework/ruby/README.mdx
docs/quick-starts/framework/ruby/_for-tutorial.mdx
docs/quick-starts/framework/sveltekit/README.mdx
docs/quick-starts/framework/sveltekit/_for-tutorial.mdx
docs/quick-starts/framework/webflow/README.mdx
docs/quick-starts/framework/webflow/_for-tutorial.mdx

Add 11 SDK docs into programmed tutorials
1. Angular
2. Capacitor JS
3. Chrome extension
4. Java Spring Boot
5. Next.js (App Router)
6. Auth.js (NextAuth)
7. Nuxt
8. Passport.js
9. Ruby
10. Sveltekit
11. Webflow

refactor: add sdk docs for tutorial

---

docs/quick-starts/framework/wordpress-plugin/_integration.mdx

as our plugin is now live in the WordPress directory

chore: update wp content

---

docs/concepts/core-service/README.mdx

refactor: update oidc rfc list

---

package.json
pnpm-lock.yaml

chore: bump dependencies

---

package.json
pnpm-lock.yaml

Fix the issue that causes mermaid subgraph text content failed to render.
Local dev test:

fix: mermaid subgraph should render text content properly

---

i18n/de/code.json
i18n/es/code.json
i18n/fr/code.json
i18n/ja/code.json
i18n/ko/code.json
i18n/pt-BR/code.json
i18n/zh-CN/code.json
i18n/zh-TW/code.json

Add missing i18n translations in inkeep AI bot

fix: add missing i18n translations

---

docs/security/captcha/recaptcha-enterprise.md

Add reCAPTCHA enterprise docs.

feat: add recaptcha enterprise doc

---

docs/security/captcha/recaptcha-enterprise.md
docs/security/captcha/turnstile.md

feat: add turnstile doc

---

docs/security/captcha/README.md
docs/security/captcha/recaptcha-enterprise.md
docs/security/captcha/turnstile.md

feat: add captcha docs

---

docs/quick-starts/framework/next-auth/_get-user-information.mdx
docs/quick-starts/framework/next-auth/_integration.mdx
docs/quick-starts/framework/next-auth/api-resources/code/_config-organization-code.md
docs/quick-starts/framework/next-auth/api-resources/code/_config-resources-code.md
docs/quick-starts/framework/next-auth/api-resources/code/_config-resources-with-scopes-code.md
docs/quick-starts/framework/next-auth/api-resources/code/_config-resources-with-shared-scopes-code.md

Update next-auth quick start, use official Logto provider in next-auth package.

fix: use official logto provider in next-auth

---

docs/security/README.mdx

fix: security page title

---

translate.shared.mjs

Print more debug logs in the content generation CI workflow, since the previous issue persists. Will remove later.

chore: print more debug logs in CI

---

docs/end-user-flows/one-time-token.mdx
i18n/de/docusaurus-plugin-content-docs/current/end-user-flows/one-time-token.mdx
i18n/es/docusaurus-plugin-content-docs/current/end-user-flows/one-time-token.mdx
i18n/fr/docusaurus-plugin-content-docs/current/end-user-flows/one-time-token.mdx
i18n/ja/docusaurus-plugin-content-docs/current/end-user-flows/one-time-token.mdx
i18n/ko/docusaurus-plugin-content-docs/current/end-user-flows/one-time-token.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/end-user-flows/one-time-token.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/end-user-flows/one-time-token.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/end-user-flows/one-time-token.mdx

Update magic link feature available version number in OSS.

refactor: update magic link available oss version number

---

docusaurus.config.ts

Remove Google Analytics and MS Clarity

refactor: remove gtag and clarity tracking tools

---

docs/integrations/social/google/_integration.mdx

chore: update google one tap docs

---

docs/quick-starts/framework/nuxt/README.mdx

Update docs according to [@logto/nuxt@1.2.3](https://github.com/logto-io/js/compare/@logto/nuxt@1.2.1...@logto/nuxt@1.2.3)
Relates https://github.com/logto-io/js/pull/918

docs(nuxt): update server api example

---

src/components/Topbar/index.module.scss
src/components/Topbar/index.tsx
src/theme/BlogLayout/index.module.scss
terms/custom.scss

Fix CSS styles on "Terms of service" page

fix: css topbar styles on terms of service page

---

docs/security/blocklist.md
docs/security/captcha/README.md
docs/security/password-policy.mdx

feat: add email blocklist doc

---

docusaurus-tutorials.config.ts

should use the correct url for meta tags

fix: update tutorials site url

---

translate.openai.mjs

Use GPT-4.1 model for i18n translation

chore: use gpt-4.1 for i18n translation

---

translate.openai.mjs

Read openai model name from env

chore: read model name from env

---

docs/user-management/user-migration.mdx

Add `Legacy` password hashing guide.

docs: add legacy password hashing

---

docs/use-cases/authorization/rbac-in-practice.mdx
docs/use-cases/multi-tenancy/build-multi-tenant-saas-application.mdx

refactor: update links in rbac and multi-tenancy use-case guides

---

docs/quick-starts/third-party/oidc/_quick-starts-reference.md
docs/use-cases/ai/enable-third-party-ai-agent-access.mdx
docs/use-cases/ai/fragments/_configure-third-party-ai-agent.mdx
docs/use-cases/ai/mcp-server-enable-third-party-ai-agent-access.mdx

complete third-party ai agent use case

docs: add third-party ai agent use case

---

docs/quick-starts/framework/go/api-resources/_fetch-organization-token-for-user.mdx

update fetching an access token for an API resource in an organization usage guide.

refactor: update go sdk guide

---

docs/authorization/validate-access-tokens/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/ko/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/authorization/role-based-access-control.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx

chore: add heading ids

---

docs/authorization/validate-access-tokens/README.mdx
i18n/de/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/es/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/fr/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/ja/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/ko/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/pt-BR/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx
i18n/zh-TW/docusaurus-plugin-content-docs/current/authorization/validate-access-tokens/README.mdx

remove redundant urls in validate access tokens home page and add jwt auth wiki page

chore: remove redundant urls

---

docs/end-user-flows/organization-experience/invite-organization-members.mdx

Update the organization invitation implementation guide.

docs: update the organization invitation guide

---

docusaurus-common.config.ts
i18n/de/code.json
i18n/es/code.json
i18n/fr/code.json
i18n/ja/code.json
i18n/ko/code.json
i18n/pt-BR/code.json
i18n/zh-CN/code.json
i18n/zh-TW/code.json
src/theme/Footer/Layout/index.tsx

- add i18n selector for better experience (the current selector in footer is inconspicuous)
- update hosted regions to "Security" to match the website update

refactor: add i18n selector and update footer

---

docs/developers/custom-token-claims/create-script.mdx

Add user interaction context instruction to the custom token claims doc.

feat(docs): add user interaction context instruction

---

src/scss/custom.scss
src/theme/BlogPostItem/Header/TitleWithSelectionDropdown/index.module.scss

Improve paddings of the doc components

fix: improve component paddings

---

docs/integrate-logto/README.mdx
docs/integrate-logto/integrate-logto-into-your-application/README.mdx
docs/integrate-logto/saml-app/attribute-mapping.mdx
docs/integrate-logto/third-party-applications/README.mdx
docs/integrate-logto/third-party-applications/permission-management.mdx
docs/logto-cloud/tenant-settings.mdx

1. README: add section of SAML app
2. SAML app > Attribute mappings:  add link of user data
3. Third-party app > Permissions management: Add default OIDC permissions
4. Third-party app: Add a FAQ about user permissions
5. Logto cloud: add how to enable MFA / SSO for tenant

refactor: update applications and cloud

---

docs/integrate-logto/interact-with-management-api/README.mdx
docs/logto-oss/troubleshooting-oss.mdx

refactor: update management api identifier

---

docs/user-management/manage-users.mdx

1. Add users steps
2. View and update the user profile
3. Reset user password

refactor: update user management

---

docs/logto-cloud/tenant-settings.mdx

Logto Cloud > Tenant settings:
1. Add "Create a tenant" and "Tenant settings"
2. Add "Leave tenant" and "Delete tenant"
3. Add a FAQ for "Export or migrate between Logto tenants"

chore: update tenant settings

---

docs/end-user-flows/account-settings/by-account-api.mdx

Add docs of updating user password

fix: add update user password

---

package.json
pnpm-lock.yaml

Ran `pnpm audit --fix` to bump transient dependencies.

chore: pnpm audit fix

---

docs/integrations/social/facebook/README.mdx
docs/integrations/social/facebook/_integration.mdx
docs/integrations/social/github/README.mdx
docs/integrations/social/github/_integration.mdx
docs/integrations/social/google/README.mdx
docs/integrations/social/google/_integration.mdx

1. Google
2. GitHub
3. Facebook

refactor: update social connector for token storage

---

docs/integrations/social/oauth2/README.mdx
docs/integrations/social/oauth2/_integration.mdx
docs/integrations/social/oidc/README.mdx
docs/integrations/social/oidc/_integration.mdx

1. Social: OIDC connector
2. Social: OAuth 2.0 connector

refactor: update standard connector for token storage

---

docs/introduction/README.mdx
docs/secret-vault/README.mdx
docs/secret-vault/federated-token-set.mdx

1. Use sentence case for "secret vault"
2. Use "third-party token" to replace "federated token"
3. Add use cases 
4. Add token storage to Introduction (Home page)

chore: optimize token storage docs

---

docs/end-user-flows/mfa/configure-mfa.mdx
docs/end-user-flows/sign-up-and-sign-in/reset-password.mdx
docs/end-user-flows/sign-up-and-sign-in/social-sign-in.mdx
docs/integrations/sms/aliyun-sms/README.mdx

1. Update Aliyun SMS tutorial: Add the description for "Phone Region Number Check"
2. Add related cases to SIE:
- Social sign-in: Add "Link or unlink social accounts" and "Store tokens and call third-party APIs"
- Reset password: Add "Has password"
- MFA: Add "Set up MFA via Account API"

chore: update docs in aug 2

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/quick-starts/generic/traditional/README.mdx

I had a problem when using this demo case. I got undefined for OIDC response again and again and found the issue was on the requester.
We need to use .json() to format the result.

fix: update traditional app integration guide

---

docs/end-user-flows/account-settings/by-account-api.mdx
docs/logto-cloud/custom-domain.mdx
docs/user-management/manage-users.mdx
docs/user-management/user-data.mdx

1. Update Account API docs:
- revise adding passkey Related Origins endpoint
- add API URL for endpoints
- add more information, e.g., custom data, verification record ID TTL, multiple passkeys, 10 backup codes
2. Delete an useless image of custom domain

refactor: update account api docs

---

docs/end-user-flows/one-time-token.mdx

docs: update magic link doc FAQs by adding assigning roles via m-api

---

docs/customization/custom-css.mdx
docs/customization/match-your-brand.mdx

Update docs about the app-level and org-level custom branding settings.

docs: update app-level and org-level customization options

---

docs/end-user-flows/account-settings/by-account-api.mdx
docs/end-user-flows/mfa/authenticator-app-otp.mdx
docs/end-user-flows/mfa/backup-codes.mdx
docs/end-user-flows/mfa/email-mfa.mdx
docs/end-user-flows/mfa/sms-mfa.mdx
docs/end-user-flows/mfa/webauthn.mdx

chore: optimize mfa docs

---

package.json
pnpm-lock.yaml

fix: security issues audit fix

---

docs/logto-cloud/custom-domain.mdx

add troubleshooting section for Cloudflare connection timeout

docs: add troubleshooting section for Cloudflare connection timeout

---

docs/quick-starts/generic/machine-to-machine/fragments/_basics-about-access-token-request.mdx

improve basic auth description

refactor: improve basic auth description
